### ISSUE TITLE
Implement responsive grid

### ISSUE THREAD

**Issue by frankiefu** [PolymerElements/app-layout#120]
Using CSS custom properties and media queries to build a responsive grid container component.

**Comment by blasten** [comment]
:+1:

**Comment by frankiefu** [comment]
Waiting for a a fix in Polymer so it would respect `@media` rules.  The branch for the fix is here: https://github.com/Polymer/polymer/tree/media-queries

**Comment by allenmoatallen** [comment]
:+1:

**Comment by frankiefu** [comment]
Please try with this [branch](https://github.com/Polymer/polymer/tree/mixins-as-custom-properties) in Polymer.
