### ISSUE TITLE
Cannot expand content in app-header to fill view

### ISSUE THREAD

**Issue by kenchris** [PolymerElements/app-layout#167]
```
<app-header condenses fixed>
          <app-toolbar>
            ...
        </app-header>
        <div class="flex">...</div>
         <footer>I'm always at the bottom</footer>
</app-header>
```

The div should expand such that it and the footer fills the view. I have tried using vertical layout on the app-header etc The app-header also doesn't fill the whole view, unless I set ```height: 100vh```

**Comment by kenchris** [comment]
https://jsbin.com/yawenuzopo/1/edit?html,output

**Comment by blasten** [comment]
It seems like we need a mixin to style the content container from `app-header-layout`. Another way to achieve this layout is to just add `app-header` and the content to `body` or anything other than `app-header-layout`.

**Comment by kenchris** [comment]
@blasten I don't follow you. Are you saying that it would work if I remove the app-header-layout? (it doesn't)

**Comment by blasten** [comment]
yes. 
```html
<body class="layout vertical" style="min-height: 100vh; margin: 0px; padding: 0px;">
  <app-header></app-header>
  <div class="flex"> content </div>
  <footer></footer>
</body>

**Comment by kenchris** [comment]
Hmm, it is not that easy that this is a components inside body which is inside an app-drawer-layout as well. https://webnfc-shoppingcart.appspot.com/#!/home

This used to be quite easy with the paper-elements, so it would be nice it would be it with app-layout as well.

**Comment by NeilujD** [comment]
@blasten It would be nice in deed to add at least a mixin to the `#contentContainer` div in the `app-header-layout` element.
However it is still possible to use the `paper-scroll-header-panel` instead of the `app-header-layout` to have this work.

**Comment by frankiefu** [comment]
@kenchris You can set `--layout-fixed-bottom` on the footer to make it fixed on the bottom, e.g.
https://jsbin.com/tamigemupu/edit?html,output

Let me know if this is what you are looking for.

**Comment by kenchris** [comment]
@frankiefu That is not it unfortunately. 

I want it 
- stuck to the buttom of the content (ie. is content is bigger than viewport and requires scrolling, the footer should scroll with it and not be fixed to the viewport.
- should expand the viewport content such that the footer is at the bottom when there is no scrolling

**Comment by frankiefu** [comment]
You can set a `min-height` on the `content` to make it fills the area, something like this:
http://jsbin.com/wufozaseva/edit?html,output

**Comment by kenchris** [comment]
Yes, that is workable but also quite inflexible when things change, as this involves manual sizing.

It would be much nicer to have the content expand to the available view and then have the item before the footer flex (expand to available size) pushing the element to the bottom.

**Comment by mbleigh** [comment]
+1 to this, I'm trying to use a `neon-animated-pages` as the content for the `app-header-layout` and I'm struggling to get anything that works like I'd like.

**Comment by NicolasRannou** [comment]
+1 trying to use an element using `iron-list` in the `content` and things become pretty messy.

**Comment by blasten** [comment]
I think it might be worth making what @kenchris suggested the default behavior of app-header-layout because app-drawer-layout already does that https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/app-drawer-layout.html#L125-L131

**Comment by blasten** [comment]
This issue is fixed in master. Here's the example: https://github.com/PolymerElements/app-layout/blob/master/app-header-layout/demo/footer.html

**Comment by blasten** [comment]
Closing this issue since it was fixed and tagged already. Feel free to reopen if you have any question.
