### ISSUE TITLE
Fix polylint errors

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/app-layout#187]
Polylint errors:

<img width="497" alt="screen shot 2016-05-01 at 13 23 37" src="https://cloud.githubusercontent.com/assets/1007051/14941550/045ba1da-0fa0-11e6-95f0-fa2e50b10540.png">

**Comment by blasten** [comment]
This is an issue in Polylint: https://github.com/PolymerLabs/polylint/issues/97
