### ISSUE TITLE
Slow style recalculation with iron-pages

### ISSUE THREAD

**Issue by NicolasRannou** [PolymerElements/app-layout#191]
I want to use app layout to display a huge list in a page and another simple page on tap.

It is fast to go from the list to the simple page but very slow to go from the simple page to the huge list because of styles recalculations it seems.

http://jsbin.com/kosodamomo/3/edit?html,output

**Comment by NicolasRannou** [comment]
neon-animated pages seems much better performance wise in this case - is it the recommended way?

**Comment by frankiefu** [comment]
This doesn't seem to be an issue in app-layout, and instead seems to be more related to iron-list.  When I inspected the iron-list in your jsbin, I saw iron-list is rendering all the items (iron-list is a virtual list and it should render only items that are needed.)
