### ISSUE TITLE
[app-drawer] shouldn't close with persistent to true

### ISSUE THREAD

**Issue by jorgecasar** [PolymerElements/app-layout#207]
### Description
The `app-drawer` doesn't have to be closed when persistent is true, becuase it's means that the `drawer-layout` is narrow. The old `paper-drawer-panel`, detects if the drawer-panel is narrow and then never close he drawer.
Yo have to check the persistent status every time. Like here: https://github.com/PolymerElements/app-layout/blob/master/templates/publishing/src/blog-app.html#L323-L325

I guess that close method should do this check. If you change the `opened `property then it's your business check persistent property, but calling the method is component responsibility does't close it self.

### Expected outcome

Close function doesn't close the drawer when the menu is persistent.

### Actual outcome

Changing the property closed to true it close itself even with persistent property true.

### Live Demo

https://polymerelements.github.io/app-layout/templates/getting-started/

### Steps to reproduce

In the Live Demo:
1. Open the console
2. Select `app-drawer` node
3. Be sure that property `persistent` is true. (width dependent)
2. Call method `$0.close()`.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by keanulee** [comment]
The design of `app-drawer` is that it can be used outside of `app-drawer-layout`, and if you're using `app-drawer-layout` then you shouldn't need to use the `close()` method on `app-drawer`. However, the `close()` method should always set the `opened` property to false (`persistent` doesn't mean the drawer can't be closed, it just means it can't be swiped closed and doesn't have a scrim). Users of `close()` could just check the `persistent` property themselves.
