### ISSUE TITLE
Persistent attribute should notify

### ISSUE THREAD

**Issue by samuelli** [PolymerElements/app-layout#209]
For example, I want to create a drawer button which appears when the drawer is not persistent. Using the opened attribute means the button disappears when the drawer is toggled (causes layout).

I'd like to be able to use persistent={{drawerPersistent}}

**Comment by keanulee** [comment]
@samuelli The persistent property is never changed by `app-drawer` itself, but is instead changed by something outside (e.g. `app-drawer-layout`). Because of this, we don't set notify to avoid the firing of unnecessary events. Is there another way you can determine the value of persistent and style based on that?

**Comment by samuelli** [comment]
I see. AFAIK, there's nothing which either emits an event or data when this persistent attribute is changed (by app-drawer-layout).

As such, doesn't look like it this is possible.

**Comment by keanulee** [comment]
`app-drawer-layout` sets persistent based on two properties - `responsiveWidth` and `forceNarrow`. If you're not using `forceNarrow`, then the best way to show/hide your button is using a media query:

```css
@media (min-width: 641px) {
  button {
    display: none;
  }
}
```

If you are toggling `forceNarrow`, then you can, at the same time, toggle some attribute/class on the button and style on that.

**Comment by samuelli** [comment]
I see. Seems acceptable but also sub-optimal since you have to duplicate the responsiveWidth.

Closing this, but may be worth thinking about exposing an event in `app-drawer-layout`.
