### ISSUE TITLE
Design proposal: rename app-scrollpos-control to app-scroll-position

### ISSUE THREAD

**Issue by cdata** [PolymerElements/app-layout#214]
_This is a vote to avoid potentially ambiguous abbreviation and accept only meaningful words for use in tag names._

I would like to propose that `app-scrollpos-control` be renamed to `app-scroll-position` (or similar). My rationale:

- `scrollpos` is not a word
- `pos` is a potentially ambiguous abbreviation of the word `position`
- `control` is a very broad concept; it could mean `widget` or `component`, or it could suggest a `controller`-like construct. This does not add notable value to the tag name, but increases its length quite a bit.
- `app-scroll-position` is easy to read and understand, while containing fewer characters

If there is a better alternative to `app-scroll-position`, I'm down for it.

**Comment by abdonrd** [comment]
I like it! 👍

**Comment by blasten** [comment]
@cdata wdyt about `app-scroll-manager`?

**Comment by maria-le** [comment]
i like this proposal. i vote for `app-scroll-position`.

**Comment by keanulee** [comment]
Coming soon - renamed in #335. Thanks!
