### ISSUE TITLE
Offer a property to app-drawer scrollable

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/app-layout#219]
In the app-drawer documentation:

> To make the contents of the drawer scrollable, create a wrapper for the scroll content, and apply height and overflow styles to it.
>
> ```
> <app-drawer>
>   <div style="height: 100%; overflow: auto;">
>     Content here.
>   </div>
> </app-drawer>
> ```

Why not offer a property to do this? Like:

```
<app-drawer scrollable>
    Content here.
</app-drawer>
```

**Comment by keanulee** [comment]
@abdonrd Because that adds complexity to `app-drawer` it doesn't need, and adding a scrolling region is simple enough that should be left to the user.

**Comment by abdonrd** [comment]
But usually you will want to have scroll, no?

Because if you have a slightly larger menu, a landscape mobile is cut.

**Comment by keanulee** [comment]
You may have a small menu that doesn't need scrolling, or you may have a fixed header at the top that doesn't scroll. Either way, this is left to the user.
