### ISSUE TITLE
<app-scrollpos-control> doesn't work with <app-header-layout has-scrolling-region>

### ISSUE THREAD

**Issue by dkipp** [PolymerElements/app-layout#227]
app-scrollpos-control has no effect when has-scrolling-region attribute is set on the app-header-layout

### Expected outcome
To scroll the view, or document that it just works with the window scrollbars and not fully supports the app-layout features

### Actual outcome
it behaves like there is no app-scrollpos-control on the site

thank you all

**Comment by frankiefu** [comment]
Currently `app-scrollpos-control` supports only [document scroller](https://github.com/PolymerElements/app-layout/tree/master/app-scrollpos-control).  The idea is if you are using document scroll then you have no alternative but to use the same scrolling region for all pages.  So `app-scrollpos-control` helps to save and restore the scroll position.  And if you are not using document scroll, then each page can have it's own scrolling region and that will automatically retain the scroll position when you switch pages.  But it's true if you are using `<app-header-layout has-scrolling-region>` and you put the pages inside `<app-header-layout>`, then you are force to use the same div scroller for all the pages.  I will mark this as enhancement and we will consider supporting it.

**Comment by Zecat** [comment]
There's an element for that!

With iron-scroll-target-behavior implemented in app-scrollpos-control, you can do
```javascript
app.$.scrollposControl.scrollTarget = app.$.headerLayout.$.contentContainer;
```
