### ISSUE TITLE
Extract scroll method to behavior

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/app-layout#228]
### Description

I am currently working with scrolling to a certain region. Applayout has a helper method to smoothly scroll to a certain position. However, since I am not using app-layout I can not access this function. Could the `Polymer.AppLayout.scroll` method maybe be placed inside a behavior in a separate repository? Elements could then inherit the smooth scrolling by integrating the behavior without the need to download the whole app-layout repository.

While browsing for elements that enable scrolling, I discovered https://github.com/PolymerElements/iron-scroll-target-behavior. Maybe the smooth scrolling can be integrated there?

**Comment by blasten** [comment]
@TimvdLippe what about if you just import `helpers/helpers.html`? That way none of the app-layout elements would be imported.  I don't think that this utility function belongs to iron-scroll-target-behavior. It more like a general utility.

**Comment by TimvdLippe** [comment]
As the file was called `helpers`, I assumed it was some internal implementation used by the app-layout elements. It just feels weird to download all off these extra elements, for just 1 single (slightly unrelated) function. I will duplicate this single function for now as our application does not need the other AppLayout related functionality.

**Comment by blasten** [comment]
Sounds good to me. We should review this topic for the next major release.

**Comment by TimvdLippe** [comment]
I am using https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView with `behavior: 'smooth'` which seems to be working just fine. Therefore closing this issue.
