### ISSUE TITLE
app-drawer-layout: Unable to get the latest code from master using bower install --save PolymerElements/app-layout

### ISSUE THREAD

**Issue by cherukumilli** [PolymerElements/app-layout#231]
### Description
app-drawer-layout: Unable to get the latest code from master using `bower install --save PolymerElements/app-layout`

### Expected outcome
`bower install --save PolymerElements\app-layout` is pulling `app-drawer-layout` code with `_narrow` hidden property instead of `narrow` property
Code fixed in #217 is not getting installed.

``` html
      properties: {
        /**
         * If true, ignore `responsiveWidth` setting and force the narrow layout.
         */
        forceNarrow: {
          type: Boolean,
          value: false
        },
        /**
         * If the viewport's width is smaller than this value, the panel will change to narrow
         * layout. In the mode the drawer will be closed.
         */
        responsiveWidth: {
          type: String,
          value: '640px'
        },
        /**
         * Returns true if it is in narrow layout. This is useful if you need to show/hide
         * elements based on the layout.
         */
        narrow: {
          type: Boolean,
          readOnly: true,
          notify: true
        }
      },
```
### Actual outcome
``` html
      properties: {
        /**
         * If true, ignore `responsiveWidth` setting and force the narrow layout.
         */
        forceNarrow: {
          type: Boolean,
          value: false
        },

        /**
         * If the viewport's width is smaller than this value, the panel will change to narrow layout.
         * In the mode the drawer will be closed.
         */
        responsiveWidth: {
          type: String,
          value: '640px'
        },

        _narrow: Boolean
      },
```

### Live Demo
Good in the master branch below is not getting installed using `bower install --save PolymerElements\app-layout`
https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/app-drawer-layout.html

### Steps to reproduce
1. Go to the terminal window
2. Go to your project folder
3. Enter `bower install --save PolymerElements/app-layout`
4. Open file `bower_components/app-layout/app-drawer-layout/app-drawer-layout.html`

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by cherukumilli** [comment]
@keanulee 
Can you please take a look at this problem?
does the archive need an update?

**Comment by frankiefu** [comment]
We haven't tagged a new release yet, will probably do one soon like this week.  In the meantime you can get the latest from master using `#master`, e.g.
`bower install PolymerElements/app-layout#master`
