### ISSUE TITLE
Title element disappears on page re-rendering

### ISSUE THREAD

**Issue by AlexNasonov** [PolymerElements/app-layout#233]
### Description
I have created a layout:
```
 <app-drawer-layout>
            <app-drawer id="startDrawer">
                <main-menu pages="[[pages]]"></main-menu>
            </app-drawer>
            <app-drawer id="endDrawer" align="end" swipe-open>
                <itef-info></itef-info>
            </app-drawer>

            <app-header-layout>
                    <app-header id="header" condenses reveals
                                effects="waterfall  resize-title  blend-background parallax-background">
                        <app-toolbar>
                            <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
                            <p condensed-title class="small-title">{{condTitle}}</p>
                            <paper-icon-button icon="info" on-click="_toggleEndDrawer"></paper-icon-button>
                        </app-toolbar>

                        <app-toolbar class="tall">
                            <h1 title class="big-title">{{title}}</h1>
                        </app-toolbar>
                    </app-header>

                <app-content page="[[contentPage]]" details="[[contentPageDetails]]" pages="[[pages]]"></app-content>
                <app-footer></app-footer>

            </app-header-layout>
        </app-drawer-layout>

    </template>
```
I have navigation buttons in `<main-menu>`, that chage URL. Change is observed by `<app-routing>` element. Accrding to URL it changes properties of `<app-content>` component.
App-content code is a collection of dom-if templates, like:
```
<template is="dom-if" if="{{pageHome}}">
            <home-content></home-content>
        </template>
        <template is="dom-if" if="{{pageAbout}}">
            <about-content></about-content>
        </template>
```

### Actual outcome

When I switch between the dom-if elements by menu buttons the`<h1 title class="big-title">{{title}}</h1>` element in header disappears. It is still in page code, but not shown. It appers again only on page refresh. This happens in Chrome but works fine in Edge.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by AlexNasonov** [comment]
BTW noticed that it happens with all `app-toolbar` and `paper-toolbar` elements on the page. They become transparent, sort of...

**Comment by blasten** [comment]
@AlexNasonov what about if you take out the `resize-title` effect?

**Comment by frankiefu** [comment]
@AlexNasonov, are you still seeing the issue with the latest release?

**Comment by AlexNasonov** [comment]
Actually I redisigned my app, so I don't use this feature anymore, so I cannot test it right now

**Comment by frankiefu** [comment]
Thanks for the response.  I will close this for now.  If you encounter the issue later please file it again.
