### ISSUE TITLE
Polylint issue: property isAttached not found in 'properties' 

### ISSUE THREAD

**Issue by web-padawan** [PolymerElements/app-layout#235]
When trying to lint project with `polylint` I'm getting this error.
```
vendor/app-layout/app-header-layout/app-header-layout.html:108:3
    Property isAttached not found in 'properties' for element 'app-header-layout'
vendor/app-layout/app-header/app-header.html:337:3
    Property isAttached not found in 'properties' for element 'app-header'
```
It's likely that you should define this property, as it is used in observer.

**Comment by motss** [comment]
This should explain why. #128

**Comment by keanulee** [comment]
@motss is correct - this is an issue with polylint, since `isAttached` is a property set by Polymer.
