### ISSUE TITLE
Improve docs on app-scrollpos-control/ app-scroll-position

### ISSUE THREAD

**Issue by motss** [PolymerElements/app-layout#239]
`selected` property on the `app-scrollpos-control` or `app-scroll-position` is too empty.
Should include examples like the property accepts the following values:
- `page`
- `page/subpage` (found in [publishing template](https://github.com/PolymerElements/app-layout/blob/master/templates/publishing/src/blog-app.html#L163))

**Comment by frankiefu** [comment]
Closing this since `app-scrollpos-control` is no longer in the repo.
