### ISSUE TITLE
title attribute on app-toolbar breaks children title attributes

### ISSUE THREAD

**Issue by jodekirk** [PolymerElements/app-layout#243]
Using the `title` attribute in the app-layout app-header is breaking the children element's `title` attributes. The children should be allowed to use the `title` attribute without issues.
https://www.w3.org/TR/WCAG20-TECHS/H33.html

I use the `title` attribute on all of my buttons as it displays a supplemental tooltip on mouse over.

```
<app-header reveals>
<app-toolbar>
  <div class="heading" title>Website Title</div>
  <paper-input id="filterText" bind-value="{{filterText}}" type="text" value="{{filterText}}" placeholder="Search DB" title="Example: Type a doc # or date (Case-sensitive)"></paper-input>
  <paper-icon-button id="gotoBtn" on-tap="getDocsSend" icon="search" title="Go To"></paper-icon-button>
  <div class="spacer"></div>
  <paper-icon-button icon="help" on-tap="toggle" class="helpBtn"></paper-icon-button>
</app-toolbar>
</app-header>
```

Proposed solution: use `class="title"` instead of `title` attribute. This is what `paper-toolbar` does and that is working fine with child elements with `title` attributes.

Using a `title` attribute is already an accepted attribute in HTML 5 so it is blocking the default of displaying a tooltip in Chrome.

I found this issue when trying to convert a `paper-toolbar` to `app-header` with `app-toolbar` and nothing worked until I removed the `title` attributes from the child elements.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
Thanks for the report.  We should probably use another attribute or a class for this.

**Comment by blasten** [comment]
It could be renamed to `main-title` since app-toolbar already has `condensed-title`

**Comment by blasten** [comment]
Fixed in master.
