### ISSUE TITLE
Out of date type annotation

### ISSUE THREAD

**Issue by sparhami** [PolymerElements/app-layout#244]
### Description
The scroll effects implementations use a type annotation for a type that is no longer present (`Polymer.AppLayout.ElementWithBackground `). For example, see this file: 

https://github.com/PolymerElements/app-layout/blob/master/app-scroll-effects/effects/blend-background.html#L19

**Comment by blasten** [comment]
The externs have been moved to https://github.com/google/closure-compiler/blob/master/contrib/externs/polymer-1.0.js, but they are missing the  [app layout ones](http://github.com/PolymerLabs/polymer-externs/blob/234fcfab2e620f52e38d30f11ca911217ec86930/polymer.externs.js ).

cc @rictic @e111077

**Comment by blasten** [comment]
Fixed via https://github.com/google/closure-compiler/commit/26ed8e908ccea7b64dfdcf1ecf6625ef9abf2b13
