### ISSUE TITLE
drawer initially open when using app-drawer-layout

### ISSUE THREAD

**Issue by jbutz** [PolymerElements/app-layout#245]
### Description
When using the app-drawer-layout on my screen the drawer is opened by default.
This appeared to be in conflict the expected default for opened.
After digging around I found what appeared to be a logic error.

### Expected outcome
Drawer is initially closed when the page is loaded

### Actual outcome

Drawer is initially open and does not have a transparent backdrop

### Live Demo

https://jsbin.com/diqicirasu/edit?html,output

### Steps to reproduce

1. Add an app-drawer-layout to a page
2. The drawer will be open

### Browsers Affected
- [X] Chrome
- [X] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Hi @jbutz 

This is not a bug - `app-drawer-layout` provides responsive functionality where a drawer will be made `opened` and `persistent` if the viewport is wide enough for a split screen layout. If you don't want the drawer to be opened initially, consider setting the `forceNarrow` property or just using the `app-drawer` element itself.

**Comment by jbutz** [comment]
Ok, gotcha. Thanks for clearing this up.
