### ISSUE TITLE
app layout broken in safari

### ISSUE THREAD

**Issue by platinumindustries** [PolymerElements/app-layout#250]
### Description
I think the app layout might be broken in Safari browsers 
### Expected outcome

I expect the drawers to be closed when I force the narrow layout.

### Actual outcome

The drawers are hidden in Chrome but fail to display correctly in safari

### Steps to reproduce

`<app-drawer-layout fullbleed force-narrow="true">
      <app-drawer swipe-open="true">
        <div style="height: 100%; overflow-y: auto;">
          hello
        </div>
      </app-drawer>
      <div style="height: 100%;">
        <pl-app-loader id="appLoader" url="ajax.php"></pl-app-loader>
      </div>
      
    </app-drawer-layout>`
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [-] Safari 9
- [-] Safari 8
- [-] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Can't reproduce - are you sure you included webcomponents-lite.js?

http://jsbin.com/renawif/edit?html
