### ISSUE TITLE
Is it possible to do in-header carousel?

### ISSUE THREAD

**Issue by SPAHI4** [PolymerElements/app-layout#251]
Is it possible to do in-header carousel like in google play?
![google play store redesign 100622298 primary idge png 620x413](https://cloud.githubusercontent.com/assets/1670998/16303588/1b3167e4-395a-11e6-8868-580ec4b24c75.png)

**Comment by blasten** [comment]
I don't see why you could not, but you would need to find a carousel element or implement your own.

**Comment by SPAHI4** [comment]
I mean is it possible to do it with app-header build-in effects? For example, with parallax-background?

**Comment by blasten** [comment]
those are scroll effects, so they only work for when the user scrolls. If you do have a carousel element then you could hide it without using scroll effects. Check the custom-primary demo https://github.com/PolymerElements/app-layout/blob/master/app-header/demo/custom-primary-element.html

**Comment by blasten** [comment]
I'm closing this issue for now, but feel free to reopen it you have questions about scroll effects or app-header in particular.
