### ISSUE TITLE
<app-header>/<app-toolbar> attributes (i.e. fixed/primary) not working inside <iron-pages>

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/app-layout#255]
I would like to have a different `<app-header>` for different views (instead of a universal `<app-header>` for all the views as per `app-drawer-template`). So I used `<iron-pages>` to select the different `<app-header>`. But the "fixed", "primary", etc attributes no longer working as expected. Below is the snippet of the codes:

```html
      <app-header-layout has-scrolling-region>

        <iron-pages selected="[[page]]" attr-for-selected="name">
          <app-header name="view1" condenses reveals fixed effects="waterfall">
            <app-toolbar>
              <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
              <div title>My View (1)</div>
            </app-toolbar>
            <app-toolbar primary>
              <paper-tabs attr-for-selected="name" fallback-selection="tab-1" selected={{selected}} style="width: 100%" noink scrollable>
                <paper-tab name="tab-1">Tab 1</paper-tab>
                <paper-tab name="tab-2">Tab 2</paper-tab>
              </paper-tabs>
            </app-toolbar>
          </app-header>
          <app-header name="view2" condenses reveals effects="waterfall">
            <app-toolbar>
              <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
              <div title>My View (2)</div>
            </app-toolbar>
          </app-header>
        </iron-pages>

        <iron-pages role="main" selected="[[page]]" attr-for-selected="name">
          <my-view1 name="view1"></my-view1>
          <my-view2 name="view2"></my-view2>
          <my-view3 name="view3"></my-view3>
        </iron-pages>

      </app-header-layout>
```

May I know if I am suppose to implement it this way, or there are better ways to go about this. Thanks!

Regards,
Andrew.

**Comment by motss** [comment]
@andrewspy You don't actually need to use `iron-pages` for different `app-header`s.

**Comment by motss** [comment]
@andrewspy This might help. http://jsbin.com/yobetiviku/edit?html,output

**Comment by andrewspy** [comment]
@motss I suppose you are using the `hidden` attribute to toggle the visibility of the `<app-toolbar>` inside `<app-header>`. Which means there should always be only one and only `<app-header>` inside `<app-header-layout>` element.

Am I correct?

**Comment by motss** [comment]
@andrewspy With `display: none` it will not include in the render tree. You can also do a similar result with `dom-if`. My demo shows you both ways: with `dom-if` and `hidden`.

**Comment by blasten** [comment]
@andrewspy `app-header` should be an immediate child of `app-header-layout` for reasons we should specify in the docs. e.g.

```html
<iron-pages selected="[[page]]" attr-for-selected="name">
  ...
  <app-header-layout name="view1">
    <app-header>
    </app-header>
   <my-view1></my-view1>
  </app-header-layout>
  ...
</iron-pages>
```

**Comment by andrewspy** [comment]
@blasten that's look like a more elegant solution that I am seeking. Thanks!

**Comment by andrewspy** [comment]
@blasten I have tried your proposed solution on `app-drawer-template`. It seems `<my-view1>` element is not visible (although I can see the DOM tree from the Chrome Developer Tools.

```html
<iron-pages selected="[[page]]" attr-for-selected="name">
  ...
  <app-header-layout name="view1">
    <app-header>
    </app-header>
   <my-view1></my-view1>
  </app-header-layout>
  ...
</iron-pages>
```

Not sure if it's a bug or am I missing something?

**Comment by andrewspy** [comment]
@blasten I have discovered removing `has-scrolling-region` attribute in `<app-header-layout has-scrolling-region>` resolve the problem.

**Comment by frankiefu** [comment]
This seems to be resolved, closing this.

**Comment by avances123** [comment]
You can keep `has-scrolling-region` with `fullbleed` at the same time:

<app-header-layout has-scrolling-region fullbleed>

**Comment by mercmobily** [comment]
By closing <app-header-layout> I am having the annoying side effect of having the contents *overlap* the header when scolling down and then "slightly up" (so that the app header pops up again).

Is there an easy way to prevent this?

In the "classical" way, <app-layout> contains everything, and the content won't scroll "over" app-header...

**Comment by mercmobily** [comment]
I have a question. I've been battling this one for the last 2 hours, unsuccessfully.
If I have things in the "classical" way with `app-drawer-layout` containing two elements, one `app-drawer` and one `header-layout` (which in turns will contain `app-header` as first child, and then the rest of the page), everything works with or without `has-scrolling-region`.

HOWEVER, if I do it as explained above, where `app-drawer-layout` contains `app-drawer` and then an `iron-pages element`, there is no way on earth to get `has-scrolling-region` to work? The only way for it to work (kind of) is to set `fullbleed`.

I looked into `iron-resizable-behavior.html`, trying to understand what events are involved and if it's maybe a resize problem... but I just can't come up on top of this one.

Please tell me before I break the wall in front of me with my head (it's already cracking :D )

Ta!
