### ISSUE TITLE
Use app-route title information in header

### ISSUE THREAD

**Issue by phidias51** [PolymerElements/app-layout#256]
It would be helpful if a "title" attribute (specified in the route) could be displayed in the header.  This is related to this issue: https://github.com/PolymerElements/app-route/issues/122#issuecomment-227827604

The hamburger menu would also need to be updated.  As the user navigates into the application, the hamburger menu would change to a <-.  When the user returns home, the hamburger menu would be restored.

**Comment by keanulee** [comment]
Toggling between the menu/back can be accomplished using a technique similar to Shop (example https://shop.polymer-project.org/, source https://github.com/Polymer/shop/blob/master/src/shop-app.html#L243), and the title can be text bound to the title (e.g. `<h1>{{title}}</h1>`). This app-specific functionality is left to the user of app-layout.

**Comment by phidias51** [comment]
@keanulee AFAIK the app-route doesn't have a title attribute.

**Comment by keanulee** [comment]
There's no special link between `app-route` and `app-layout`. If you want to render the route inside a heading, you could bind heading text app-route's `data` object.

```html
<app-route route="{{route}}" pattern="/:page" data="{{data}}"></app-route>
<h1>{{data.page}}</h1>
```
