### ISSUE TITLE
Internet Explorer Bugs: app-header effects

### ISSUE THREAD

**Issue by oneezy** [PolymerElements/app-layout#257]
I'm having an issue with the scroll effects. You can see the problem happening in IE10, IE11, and Edge, but Chrome, FF, and Android browsers appear to be good. 

**Live Link:** http://sulphurfuelinjection.com/
**Source Code:** https://github.com/oneezy/psk-1.5/tree/master/app/src 
**Video (pardon the commentary):** https://www.youtube.com/watch?v=7QISkTfeFRc

--

I think the problem exists with they way I'm laying everything out..though I'm unsure..the `<component-header>` is where the `<app-header-layout>` and `<app-header>` exists and I think* that's where my problem starts:

**Main Layout** [(view source)](https://github.com/oneezy/psk-1.5/blob/master/app/src/business-app.html)

    
    <component-header id="Services" grid="vertical" layout="start-stretch" min-height="1"></component-header>

    
    <component-main id="Main" grid="vertical" layout="start-stretch" min-height="1">

        <page-intro          id="Intro"       min-height="1"    flex="1"    bg="white">        </page-intro>
        <page-company        id="Company"        min-height="1"    flex="1"    bg="yellow">       </page-company>
        <page-testimonials   id="Testimonials"   min-height="1"    flex="1"    bg="gray">         </page-testimonials>
        <page-forms          id="Contact"        min-height="1"    flex="1"    bg="white">        </page-forms>
        <page-outro          id="Outro"          min-height="1"    flex="1"    bg="blue">         </page-outro>

    </component-main>

    
    <component-footer id="Footer" grid="vertical" layout="start-stretch"></component-footer>
    

**Header Component** [(view source)](https://github.com/oneezy/psk-1.5/blob/master/app/src/components/component-header.html)

            <app-header-layout>
                <app-header
                    id="appHeader"
                    class="main-header"
                    condenses
                    reveals
                    effects="resize-snapped-title waterfall blend-background parallax-background">

                    
                    
                    
                    <app-toolbar class="top-toolbar">

                        <header-toolbar grid="horizontal" layout="between" condensed-title>
                            <paper-icon-button class="toolbar-drawer" icon="menu" drawer-toggle></paper-icon-button>

                            <paper-tabs class="toolbar-links" selected="{{selected}}" attr-for-selected="name" hidden$="{{mobile}}">
                              <template is="dom-repeat" items="{{items}}">

                                <paper-tab name="{{item}}">
                                    <a href="#{{item}}">{{item}}</a>
                                </paper-tab>

                              </template>
                            </paper-tabs>
                        </header-toolbar>
                    </app-toolbar>

                    
                    
                    
                    <app-toolbar class="hero" title>
                        <header-hero></header-hero>
                    </app-toolbar>

                </app-header>

            </app-header-layout>
        </app-drawer-layout>

**Comment by keanulee** [comment]
@oneezy `app-drawer-layout` is designed to include both `app-drawer` and the main content, and `app-header-layout` is designed to include `app-header` and the content below. In this case, I would consider just using `app-drawer` and `app-header` without the corresponding `-layout` elements (which are entirely optional).

```html
<component-header>
  <!-- Shadow root -->
    <app-header></app-header>
    <app-drawer></app-drawer>
</component-header>
```

**Comment by blasten** [comment]
+1 to what @keanulee said.  Also given the structure of your app, I'd suggest renaming `component-header` as `component-shell` and have the following structure:

```html
<component-shell>
  <component-main id="Main" grid="vertical" layout="start-stretch" min-height="1">
    ... 
  </component-main>
  <component-footer id="Footer" grid="vertical" layout="start-stretch"></component-footer>
</component-shell>
```

and have a `<content></content>` distribution point inside **component-shell**. e.g.

```html
 ....
    </app-header>
    <app-drawer></app-drawer>
   <content></content>
  </app-header-layout>
</app-drawer-layout>
```

**Comment by frankiefu** [comment]
@oneezy , it this still an issue?

**Comment by oneezy** [comment]
@frankiefu , No it isn't., thanks for responding.

The problem was my grid system [property grid system]. Apparently IE **hates** that I was styling my markup with `[properties]` instead of `.class` names. Something with the way IE renders out the 2 (styling with class's is way faster!)...one of my failed experiments, but I did learn a valuable lesson :)

--------

**BAD** (was using)
```
[layout="vertical"] { display: flex; flex-direction: column; } 
<div layout="vertical">
```

**GOOD** (using now)
```
.layout-vertical { display: flex; flex-direction: column; } 
<div class="layout-vertical">
```

**BEST** (starting to use)
```
div { @apply(--layout-vertical); } 
<div>
```
--------

So... for anyone else that has a wild idea like creating an entire grid system with `[attribute="property"]'s`, take my word for it and...

# Don't do it!!
