### ISSUE TITLE
Pesto template doesn't open drawer when used locally

### ISSUE THREAD

**Issue by deibid** [PolymerElements/app-layout#262]
### Description
The Pesto demo doesn't allow complete navigation when served locally. I want to use the template to modify it locally so i can experiment a bit, but the navigation drawer does not open. When using the Github deployed version that you guys maintain, there are no issues.

### Expected outcome

A locally running application to test various aspects of the navigation practices in Polymer. 

### Actual outcome

The navigation drawer doesn't open when clicked on the menu icon, and the styling of the dropddown menu of the details page is a bit messed up.

### Live Demo

For this to happen, try locally.

### Steps to reproduce

1. Download the app-layout master repo as zip to a local machine
2. Extract the pesto folder that is under templates to another directory
3. cd into it
4. ' $ bower install ' , so that every package is fetched
5. '$ polymer serve --open '
6. Try to use the app, and you'll see that the navigation drawer does not open

*. When trying this with other templates, like the Shrine app, there are no issues.

### Browsers Affected

- [√] Chrome
- [√] Firefox
- [√] Safari 9

( didn't test others )

**Comment by keanulee** [comment]
We renamed the attribute used by app-header from `title` to `main-title` (#249), but we haven't tagged a new version yet so it's generating errors (can be fixed by pointing to `app-layout#master` in bower.json). @frankiefu Should we tag a new version now?

**Comment by keanulee** [comment]
This issue should now be fixed with v0.9.2
