### ISSUE TITLE
Ripples nearly invisible in app-drawer-layout

### ISSUE THREAD

**Issue by Steven-Roberts** [PolymerElements/app-layout#267]
### Description
The ripple effect on elements like `paper-checkboxes` and `paper-icon-buttons` are barely visible when inside an `app-drawer-layout` with the `app-drawer` open.  The `paper-drawer-panel` had an [identical issue](https://github.com/PolymerElements/paper-drawer-panel/issues/51), and it seems that it also can use the same fix.  By setting the opacity of the `app-drawer` to .99 (or anything < 1), the ripple effect is visible again.

### Live Demo
http://output.jsbin.com/qazupuvela/1

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11

**Comment by keanulee** [comment]
Can confirm that this issue exists. It isn't specific to app-layout as I can narrow it down to a `<paper-ripple  class="circle">` partially covered by a fixed element (http://output.jsbin.com/jenori), and I'm trying to narrow it down further since I believe it's a browser bug.

**Comment by keanulee** [comment]
Simpler repo case (without Polymer/webcomponentsjs): http://output.jsbin.com/tiraguy

Closing since this is a Chrome bug, not an app-layout issue. Suggest using workaround with `opacity`.
