### ISSUE TITLE
<app-drawer> is missing functionality...

### ISSUE THREAD

**Issue by rchrdnsh** [PolymerElements/app-layout#268]
I cannot find an attribute that makes the app-drawer push the content in the main view over, like a side-panel, so that the full contents of both the app-drawer and the main view are completely visible. I can only slide the app-drawer in from the side and cover the content in the main view, greying out the main view in the process. This is frustrating, as I would like to use this element for my design, but I need this functionality for the app-drawe to be useful for me.

**Comment by rchrdnsh** [comment]
A good example is the right panel in the new google fonts web app, which does exactly what I'm describing:

https://fonts.google.com

**Comment by keanulee** [comment]
Is this what you're looking for? https://elements.polymer-project.org/elements/app-layout?view=demo:app-drawer-layout/demo/simple-drawer.html&active=app-drawer-layout

**Comment by rchrdnsh** [comment]
no. the original content, which are the cards with Latin on them, do not move over when either hamburglur is pressed, but are covered and greeted out by the <app-drawer> elements. This means that the z-axis of the <app-drawer> is higher than the cards view. I want to be able to add an <app-drawer> element in the same z-axis as the content view, so that when I open the <app-drawer> the content is pushed over, so both the content of the <app-drawer> and the content of the main view are visible at the same time. Imagine the TOC of a book in the <app-drawer> and the book itself in the main view. I want to be able to navigate the TOC at the same time as I read the contents of the book. I do not want the TOC covering the contents of the book. In mobile this is not practical, but on tablet, laptop, desktop, etc...it is absolute heaven...

**Comment by rchrdnsh** [comment]
This functionality might be better served as a separate element unto itself. Maybe something like an <app-panel>, where the panel can be sown of hidden, and can enter/exit from the top, right, bottom and left if need be. The reason why I bring it up here is that the functionality would be similar, if not almost the same, to the <app-drawer> element, so it might be better to expand the capabilities of this element, verses making a new element. But I'm not sure...

**Comment by rchrdnsh** [comment]
apologies, I kept putting arrow brackets around names to be consistent with the names of the elements, but then those names disappeard! :-(

**Comment by keanulee** [comment]
You can still use app-drawer-layout, but you'll need to write your own menu button click handlers to toggle `forceNarrow` on app-drawer-layout. There's a (not very easily discoverable) demo of this in the repo https://github.com/PolymerElements/app-layout/blob/master/demo/demo6.html

**Comment by frankiefu** [comment]
@keanulee's solution should work for you so I am closing this.
