### ISSUE TITLE
<app-toolbar> not pushing icons to right of toolbar

### ISSUE THREAD

**Issue by Tykin** [PolymerElements/app-layout#269]
### Description
The [example documentation](https://www.polymer-project.org/1.0/toolbox/app-layout#simple-toolbars) shows that app-toolbar uses flex layout to push out the icons to the left and right of title in the toolbar. However, this does not happen in the example jsbin.

http://jsbin.com/mozujahele/edit?html,output

### Expected outcome

```
<app-toolbar>
    <paper-icon-button icon="menu"></paper-icon-button>
    <div title>Spork</div>
    <paper-icon-button icon="search"></paper-icon-button>
</app-toolbar>
```

Should result in the left menu button, followed by the word spork, followed by the search button on the far right side. 

### Actual outcome

The search icon is right next to the title.

### Live Demo
http://jsbin.com/mozujahele/edit?html,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by motss** [comment]
@Tykin Please use `main-title` for [latest version](https://github.com/PolymerElements/app-layout/releases/tag/v0.9.2) of `app-layout`. This is proven to work if you change it to `main-title` from `title`.

**Comment by Tykin** [comment]
@motss Thank you! That fixed the issue.
