### ISSUE TITLE
Running Polymer lint on components that uses app-drawer & app-drawer-layout returns error: isAttached not found in 'properties' for element 'app-drawer / app-drawer-layout'

### ISSUE THREAD

**Issue by tjmonsi** [PolymerElements/app-layout#270]
### Description
When running `polymer lint` or `polylint` and importing `app-drawer` & `app-drawer-layout`, returns error:
```
/bower_components/app-layout/app-drawer-layout/app-drawer-layout.html:149:3
    Property isAttached not found in 'properties' for element 'app-drawer-layout'
/bower_components/app-layout/app-drawer/app-drawer.html:173:3
    Property isAttached not found in 'properties' for element 'app-drawer'
/bower_components/app-layout/app-header-layout/app-header-layout.html:108:3
    Property isAttached not found in 'properties' for element 'app-header-layout'
/bower_components/app-layout/app-header/app-header.html:319:3
    Property isAttached not found in 'properties' for element 'app-header'
/bower_components/app-layout/app-drawer-layout/app-drawer-layout.html:149:3
    Property isAttached not found in 'properties' for element 'app-drawer-layout'
/bower_components/app-layout/app-drawer/app-drawer.html:173:3
    Property isAttached not found in 'properties' for element 'app-drawer'
/bower_components/app-layout/app-header-layout/app-header-layout.html:108:3
    Property isAttached not found in 'properties' for element 'app-header-layout'
/bower_components/app-layout/app-header/app-header.html:319:3
    Property isAttached not found in 'properties' for element 'app-header'
```

### Expected outcome
No errors from polymer lint

### Actual outcome
Errors because of missing properties in `app-drawer` or `app-drawer-layout` or even the imported behaviors `iron-resizable-behavior` (for app-drawer) 

### Steps to reproduce

1. Start polymer init
2. Set it to app-drawer-template
3. run polymer lint
4. Error

It's already an error reported in polymer-cli: https://github.com/Polymer/polymer-cli/issues/266

If you want, I can just set up a PR to add isAttached property with type Boolean

**Comment by tjmonsi** [comment]
I also just found out this https://github.com/Polymer/hydrolysis/issues/205

**Comment by motss** [comment]
@tjmonsi This should explain why. #128

**Comment by tjmonsi** [comment]
@motss figured it out as well. Anyway, I think it is best to close this for now given that it is an issue of polylint :)
