### ISSUE TITLE
Enhancements on app-grid documentation

### ISSUE THREAD

**Issue by motss** [PolymerElements/app-layout#272]
### Description

Enhancements need to be made:

1. Should state that `class="app-grid"` is needed to create a grid layout.
2. `class="app-grid"` is nowhere to be found in example of `aspect-ratio`.
3. Typo in `app-grid` example where `include="app-grid-styles"` has an extra letter s and should be corrected to `include="app-grid-style"`.
4. Typo in `expandible-items`example where only `--app-grid-expandible-item-columns` can be set and apply the mixin `--app-grid-expandible-item`.
5. Is it possible to achieve the grid layout in https://zuperkulblog.appspot.com/art/list where the grid will have `margin: auto` on both sides on wide layout making the grid to be horizontally centered?

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by blasten** [comment]
👍
