### ISSUE TITLE
Uncaught TypeError in polymer-mini.html:2044

### ISSUE THREAD

**Issue by 5amfung** [PolymerElements/app-layout#273]
### Description

I have the basic app drawer layout setup but I keep getting this from the console.

![image](https://cloud.githubusercontent.com/assets/371691/16637632/442d1f86-4395-11e6-8569-034dd3d83fd4.png)

This is the html I have:
```
<app-drawer-layout>
    <app-drawer>
        <app-toolbar style="background-color: #4285f4; color: white;">My App</app-toolbar>
    </app-drawer>

    <app-header-layout>
        <app-header reveals effects="waterfall">
            <app-toolbar>
                <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
                <div title>{{ title }}</div>
                <paper-icon-button icon="search"></paper-icon-button>
            </app-toolbar>
        </app-header>

        <!-- Main content -->
        <div class="layout vertical" style="padding: 16px;">
            <router-outlet></router-outlet>
        </div>
    </app-header-layout>

</app-drawer-layout>

```

I used https://github.com/vaadin/angular2-polymer to load the component in my angular2 project.

### Expected outcome

I expect no error from the console.

### Actual outcome

The app drawer and everything are functional but I get this error from the console.
polymer-mini.html:2044 Uncaught TypeError: Cannot set property 'persistent' of undefined

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@5amfung I'm not too familiar with angular2-polymer, but the HTML you provided above looks fine. Can you provide a live demo (e.g. JSBin) with this issue?

**Comment by JanGunzenhauser** [comment]
I'm having the same issue with almost exactly the same HTML and not using Angular.

**Comment by keanulee** [comment]
Can you repro the issue? Here's a working example of the provided code: http://jsbin.com/jogaqenupo/edit?html,output

**Comment by JanGunzenhauser** [comment]
No clue how to reproduce. I went back to using just the app-header-layout which is working fine.

**Comment by frankiefu** [comment]
@5amfung, can you provide a demo showing the issue? Something similar to @keanulee's: http://jsbin.com/jogaqenupo/edit?html,output)

**Comment by maxmumford** [comment]
I'm having this issue as well, also with angular2-polymer, so it seems likely that it's an issue with that lib instead. If I manage to solve it i'll post the solution here...

**Comment by 5amfung** [comment]
@frankiefu @keanulee Sorry for the late update.  In my environment, I used angular-cli (webpack), angular2 rc5, and angular2-polymer.  I'm kind of new to jsbin.  So I'm trying to figure out how to get all that setup with jsbin.  If there's any sample template I can use, please let me know.

Before I figure how to create a demo on jsbin, let me provide a little more context.  I was able to narrow down to this.

- When running on Chrome, if I don't wait for WebComponentsReady event and immediately bootstrap the angular app, everything works without any problem on Chrome, but not Safari.

- If I wait for WebComponentsReady before bootstrapping the app, it works on Safari, but not Chrome.  When it doesn't work on Chrome, that's where I get would get `Cannot read property 'getWdith' of undefined` from `polymer-mini.html` and `Cannot set property 'persistent' of undefined` error from `app-drawer-layout.html`.  As far as I know, we should wait for WebComponentsReady before bootstrapping the angular app.

**Comment by 5amfung** [comment]
For reference https://github.com/vaadin/angular2-polymer/issues/74
