### ISSUE TITLE
app-drawer swipe-open breaks scroll bars

### ISSUE THREAD

**Issue by samuelli** [PolymerElements/app-layout#275]
If the drawer content overflows and has a non-overlay scrollbar (eg. linux), `swipe-open` adds an pseudo-element `:after` which overlays the scrollbar, preventing the scrollbar from being clicked.

**Comment by keanulee** [comment]
@samuelli Which browsers display the scrollbar under `::after`? From what I see, Chrome and Firefox on Ubuntu put the scrollbar within the scrolling region (inside the drawer).

![image](https://cloud.githubusercontent.com/assets/1319720/16961112/f4e197ca-4da0-11e6-9447-7f1b6d22422e.png)

**Comment by samuelli** [comment]
@keanulee: This is the site I'm looking at: https://custom-elements.appspot.com/element/PolymerElements/app-layout

![image](https://cloud.githubusercontent.com/assets/787668/16971152/9767c4f6-4e64-11e6-9608-7a8e24844e39.png)

**Comment by keanulee** [comment]
I would suggest not putting `overflow: auto` in `--app-drawer-content-container`, but instead create a full height scrollable element inside of `app-drawer`.

**Comment by frankiefu** [comment]
@keanulee is correct.  The current recommended way to make drawer scrollable is to create a wrapper for the scroll content, and apply height and overflow styles to it.
```
<app-drawer>
  <div style="height: 100%; overflow: auto;"></div>
</app-drawer>
```
