### ISSUE TITLE
App-header sticky attribute scroll bug.

### ISSUE THREAD

**Issue by JessedeRuijter** [PolymerElements/app-layout#277]
### Description
When having an app-header with two app-toolbars and the last of which has the 'sticky' property. The toolbar will end-up in different places when scrolling to the top depending on how fast you scroll.

### Expected outcome
When scrolled to the top, the second tool bar will end up right below the first toolbar.

### Actual outcome
The second toolbar will end up way lower than expected. The faster you scroll, the lower it will end up.

### Live Demo
https://jsfiddle.net/JessedeRuijter/wx0rcdbk/

### Steps to reproduce
1. When having a specific header layout (open live demo).
2. Scroll down to the bottom of the element.
3. Scroll to the top of the page as fast as possible.
4. Depending on the scroll speed the sticky toolbar will end up on different locations.

### Browsers Affected

- [x] Chrome (only one tested)
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by JessedeRuijter** [comment]
I wanted to add that the viewport gets messed up as well. Even elements with a fixed position and top: 0px; are displaced.

**Comment by blasten** [comment]
That seems odd

**Comment by NoLdman** [comment]
Just ran into the same problem and can confirm it also occurs on Firefox 48, Safari 9 and IE 11.
Furthermore it seems to be to be `app-toolbar` independent, since I used two `div` elements in my project, with the latter div having the `sticky `attribute.

**Comment by frankiefu** [comment]
Here is a simple [jsbin](http://jsbin.com/hecoxuwuqu/edit?html,output) showing the issue.  When you scroll down and then scroll back up very quickly to the top, the stickyEl (the red toolbar) would be placed at a incorrect position.  I think we might need to reset the transform on the stickyEl when  the we reach the top.
