### ISSUE TITLE
Feature request: --app-grid-gutter only in the inner edges

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/app-layout#281]
### Description

Right now, the `--app-grid-gutter` adds the space in the inner and outer edges.
An option to add only in the inner edges would be great.
### Expected outcome

<img width="375" alt="app-grid-demo-2" src="https://cloud.githubusercontent.com/assets/1007051/17113128/89972314-52a9-11e6-8c29-5e8848b2379c.png">

### Actual outcome

<img width="407" alt="app-grid-demo-1" src="https://cloud.githubusercontent.com/assets/1007051/17113132/8e06d674-52a9-11e6-9a9b-d6f1b829b605.png">

### Live Demo

https://jsbin.com/mowajacidu/edit?html,output

**Comment by blasten** [comment]
I would need to revisit this issue. It wasn't particularly satisfying how that problem could be solved with the current approach. e.g. negative top and left margins + wrapper to clip the grid.

**Comment by abdonrd** [comment]
As far as I know, the Polymer Elements are not going to continue developing. So I close this issue.
