### ISSUE TITLE
paper-fab with higher z-index

### ISSUE THREAD

**Issue by sowsan** [PolymerElements/app-layout#282]
Hello -

I'm trying to implement the design as per https://material.google.com/components/buttons-floating-action-button.html#buttons-floating-action-button-floating-action-button 

Need to put the paper-fab button on top of the content page and app header (intersection) , but due to the setting in app header layout any content that I put its getting low z-index and hence paper-fab control is always covered by header. Any idea how can I fix this ? Giving higher z-index to the paper-fab no fixing this.

https://raw.githubusercontent.com/PolymerElements/app-layout/master/app-header-layout/app-header-layout.html

 #contentContainer {
        /* Create a stacking context here so that all children appear below the header. */
        position: relative;
        z-index: 0;
      }
 :host > ::content > app-header {
        @apply(--layout-fixed-top);
        z-index: 1;
      }

**Comment by keanulee** [comment]
@sowsan I think the best way is to just use app-header (without app-header-layout) and do the positioning yourself. That is, use app-header and add margin-top to the content so that it is below the header.

**Comment by sowsan** [comment]
Thank you @keanulee , if I just use app-header, does it provider the scrolling behaviors and details that currently available through app-header-layout ?

**Comment by blasten** [comment]
@sowsan app-header does include the scrolling behaviors (scroll effects). app-header-layout only helps to position the header above the content based on a given configuration.
