### ISSUE TITLE
[app-grid] Wrong math in "--app-grid-expandible-item"?

### ISSUE THREAD

**Issue by diogocamposwd** [PolymerElements/app-layout#285]
In an grid with this characteristics:

width = 480
gutter = 16
columns = 4

...the results should be:
```
1-1-1-1 = 16 [100] 16 [100] 16 [100] 16 [100] 16 = 480
    2-2 = 16 [-----216----] 16 [-----216----] 16 = 480
    3-1 = 16 [---------332---------] 16 [100] 16 = 480
      4 = 16 [--------------448-------------] 16 = 480
```

1 column = 100
2 columns = 216
3 columns = 332
4 columns = 448

...but the math in "--app-grid-expandible-item" is generating this results:

1 column = 68
2 columns = 200
3 columns = 332
4 columns = 448

Am I missing something?

**Comment by blasten** [comment]
You are right. I'm gonna submit the patch asap.
