### ISSUE TITLE
app-scroll-effects causes unsafe eval warning

### ISSUE THREAD

**Issue by srsudar** [PolymerElements/app-layout#286]
### Description

I am trying to use `app-layout` in a Chrome app. Chrome Apps have a strict CSP that prohibits inline scripts and the use of `eval`. To circumvent this I am using a custom component that includes `app-layout` and running `vulcanize --inline-scripts --inline-css indexRaw.html | crisper --html index.html --js index.js`.

This is all well and good and it works for the most part. However, `app-scroll-effects` and `app-scroll-effects-behavior` throws the following error:

```
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'sef' blob: filesystem: chrome-extension-resource".
```

The offending line [is in `app-scroll-effects-behavior.html`](https://github.com/PolymerElements/app-layout/blob/master/app-scroll-effects/app-scroll-effects-behavior.html#L283): `var noop = Function();`. I don't understand why Chrome complains about this, but switching the line to `var noop = () => {}` (effectively the same thing), works just fine.

It isn't clear to me why `Function()` would trigger unsafe eval. Maybe it's something `vulcanize` or `crisper` is doing? I wouldn't think so, however, and if so I wouldn't expect `() => {}` to fix it. If this makes sense to someone, it might be worth changing that line so that others can consume the library under more restrictive CSPs.

**Comment by blasten** [comment]
Good to know. `Function()` does accept a string as the function body. I think we can replace that with an empty function. (no ES2015 unfortunately)
