### ISSUE TITLE
app-drawer feels sluggish on Firefox Android

### ISSUE THREAD

**Issue by motss** [PolymerElements/app-layout#292]
### Description
`app-drawer` feels sluggish on Firefox Android even on the [Shop](https://shop.polymer-project.org). Any plans to improve the performance?

### Expected outcome
Opening and closing of `app-drawer` should be smooth and no stutters just like how it runs on Chrome Android.

### Actual outcome
Opening and closing of `app-drawer` is sluggish.

### Browsers Affected

- [x] Firefox
- [ ] Chrome
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
`app-drawer` uses standard browser APIs for its transitions, and it's up to browser vendors to optimize these APIs. If you notice anything that `app-drawer` can do be be more performant feel free to send a PR.
