### ISSUE TITLE
Consistency "PolymerElements" vs "polymerelements" in bower.json for webjars usage

### ISSUE THREAD

**Issue by bartolom** [PolymerElements/app-layout#293]
### Description

The `app-layout` element is using "polymerelements" in its bower.json file to reference dependecies. 

Like: `polymerelements/iron-flex-layout#^1.0.0` 

While other popular Polymer elements like `paper-checkbox`, `paper-button` use "PolymerElements"

Like `PolymerElements/iron-flex-layout#^1.0.0`

Other Polymer elements use a mixture like `app-route`

I  assume this does not matter in the JavaScript and Bower world. But I'm trying to figure out if it is possible to use Polymer-Elements in Java/JVM based micro services. In the Java world dependencies are pulled together from so called "Maven-Repositories". 

There is a very nice effort to bridge the Bower/NPM things with Maven-Repositories in the project http://www.webjars.org/ . Webjars.org works fairly well for pure javascript dependencies, but less well for PolymerElements. Many PolymerElements artifacts appear twice with the lower and upper case version of the github name "PolymerElements".

`github-com-PolymerElements-iron-flex-layout`
`github-com-polymerelements-iron-flex-layout`

This is an issue for JVM based software where letter case matters.

### Expected outcome

It would be nice if all PolymerElements would consistently use "PolymerElements" because this is the github name of the project.

`app-layout` is just the first github repo where I wrote a ticket about this, but ideally it could be consistent everywhere.

### Steps to reproduce

Look at the bower.json files of the various projects
 

- https://github.com/PolymerElements/paper-checkbox/blob/master/bower.json
- https://github.com/PolymerElements/paper-button/blob/master/bower.json
- https://github.com/PolymerElements/app-layout/blob/master/bower.json
- https://github.com/PolymerElements/app-route/blob/master/bower.json
- https://github.com/PolymerElements/iron-dropdown/blob/master/bower.json
- ...

### Browsers Affected
This does not affect bowsers. This affects Java build system like Maven, Gradle, SBT but seems to be no problem for JavaScript users that use Bower.

**Comment by abdonrd** [comment]
Maybe the best option is automatize it with [tedium](https://github.com/PolymerLabs/tedium). To has an standar `bower.json` for all the `PolymerElements`. Please, @bartolom, can you create an issue there?
