### ISSUE TITLE
Modal dialog doesn't works with app-drawer-layout

### ISSUE THREAD

**Issue by juanmendez92** [PolymerElements/app-layout#295]
### Description
When I use the modal version of the paper-dialog, the dialog is covered and I need to delete from the DOM an iron-overlay-backdrop or delete the modal attribute

### Live Demo
https://jsbin.com/likiwik/edit?html,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@juanmendez92 This is a classic stacking context issue (e.g. https://github.com/PolymerElements/paper-dialog/issues/109). For this reason, we recommend structuring your app such that the dialog is not inside another stacking context (e.g. as a direct child of `<body>`.

**Comment by robdodson** [comment]
To clarify @keanulee's answer a bit. As I understand it, your dialog _should_ be a direct child of `<body>`. This is because the paper-dialog overlay gets added to body.

Your dialog _should not_ be inside of another custom element like my-view that's nested inside of your app-drawer layout. If you do that then the overlay will end up covering your element.

**Comment by RhysyG** [comment]
Sorry to ask for clarification on a closed topic, but if your App had say 15 dialogs, would the practicality be just having 15 paper-dialogs in the index.html file?

**Comment by ergo** [comment]
@robdodson In a real-life scenario I have something like this:

        <app-drawer-layout>
            <app-header condenses reveals effects="waterfall">
                <app-toolbar>....</app-toolbar>
            </app-header>
            <app-drawer slot="drawer">....</app-drawer>
            <uirouter-uiview>...this injects view elements that will use dialogs...</uirouter-uiview>
        </app-drawer-layout>

I'd expect production applications would use routers injecting view elements inside `app-drawer-layout` there (which happens to set z-index:0 - thus breaking the functionality). I'm not sure if there is a non-hacky way to use dialogs with `app-drawer-layout`?

**Comment by robdodson** [comment]
@valdrinkoshi

**Comment by valdrinkoshi** [comment]
The only escape from the stacking-context trap is to declare the element at the Top Layer (aka document's top stacking context).
Proposals like the [Blocking Elements stack](https://github.com/whatwg/html/issues/897) are in the process of being drafted, but while waiting for it to be available, all you can do is workaround the issue.
[`<iron-overlay>`](https://github.com/PolymerLabs/iron-overlay) is based on the idea of using `<template>` to host overlay content, which `<iron-overlay>` will stamp at the right spot for you. 
I've written a codelab around this topic https://codelabs.developers.google.com/codelabs/building-custom-overlays, in particular check step 5, 6 which are around the stacking context issues.
It comes with caveats, especially on content's styling encapsulation & event bubbling.

**Comment by ergo** [comment]
@valdrinkoshi I understand, but and maybe I'm missing something, but `app-drawer-layout` sets its own z-index by default, so there is no way to have modals with default PSK?

You mention step 5 and 6 - but I'm using `paper-dialog` which is supposed to mitigate the problem as it uses `iron-overlay`.

The problem basicly means one sees the overlay backdrop - but modal is "behind" the overlay.

**Comment by valdrinkoshi** [comment]
`paper-dialog` uses `iron-overlay-behavior`, which doesn't do any reparenting - that would be a breaking change.
`iron-overlay` is an experiment on exploring the technique of hosting content in a template and stamping it in the right spot.

**Comment by ergo** [comment]
Wouldn't that essentially break event emitting? If have `foo-view` and my dialog emits event for the view - it will not work anymore I believe.

**Comment by ergo** [comment]
@valdrinkoshi Are you aware of any online examples on how to structure your application to have `app-layout` and support multiple dialogs depending on different views?

**Comment by wesalvaro** [comment]
@ergo I just got hit with this, too. Since the dialogs I care about are larger and more involved, they have their own element. What I do is fire an event from the nested element when I want the dialog opened. The top-level element listens for the event and constructs the dialog.

This is it's handler:

```js
_onDialogOpen(e) {
      const dialog = document.createElement(e.detail.dialog);
      const props = e.detail.properties;
      for (let key in props) {
        dialog.set(key, props[key]);
      }
      const root = Polymer.dom(this.root);
      dialog.addEventListener('iron-overlay-closed', () => {
        root.removeChild(dialog);
      });
      root.appendChild(dialog);
      dialog.open();
    },
```

It works alright for my use-case right now.
