### ISSUE TITLE
Two drawer desktop layout obscures main content

### ISSUE THREAD

**Issue by SMEmp** [PolymerElements/app-layout#303]
### Description ###

When using two persistent sidebars on desktop, the right drawer obscures content in the main content area.

### Expected outcome ###

> [**Desktop structure**](https://material.google.com/layout/structure.html#structure-ui-regions)

> The desktop structure contains a permanent app bar with a floating action button. The app bar absorbs elements from the tablet and mobile bottom bars. Where possible, the window controls are absorbed into the app bar.

> Side navigation menus can take up the full height of the screen size (including under the app bar) and be accessed temporarily or pinned for permanent display. Side nav menus, as well as the content canvas, can have their own secondary toolbars for tabs, palettes, or secondary actions.

![Desktop Structure sketch](https://material-design.storage.googleapis.com/publish/material_v_9/0Bx4BSt6jniD7SnotM2RNN2FFMzQ/layout_structure_regions_desktop.png)

### Actual outcome ###

Content canvas is obscured by right nav drawer.

### Live Demo ###

Based on the results of `polymer init app-drawer-template`, side navs are not below primary toolbar but otherwise similar to the "Desktop structure" mentioned in material design.

Also based on the [two drawer demo](https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/demo/two-drawers.html)

Main content area should be filled with [this alignment test image](http://hypercritical.co/2013/12/22/images/tv-overscan.png), without any corners missing.

https://jsbin.com/vofosohixo/1/edit?html,output

### Steps to reproduce

1. Put an `app-drawer-layout` component on the page.
2. Put two `app-drawer` components inside, one with `align="end"`.
3. Put some other content in the `app-drawer-layout`, preferably a large image or large amount of text.
4. Main content will be obscured by right hand drawer.

### Browsers Affected

- [X] Chrome
- [?] Firefox
- [?] Safari 9
- [?] Safari 8
- [?] Safari 7
- [?] Edge
- [?] IE 11
- [?] IE 10

**Comment by keanulee** [comment]
Hi @SMEmp. `app-drawer-layout` is designed to position only the first drawer next to the content (the split-screen layout). To accommodate the second drawer, you'll need to do that yourself (e.g. add the appropriate `margin-right` to the content and potentially respond if the right drawer closes). The code for `app-drawer-layout` can be used as a reference for building this.
