### ISSUE TITLE
iron-collapse triggers close of app-drawer

### ISSUE THREAD

**Issue by undermensch** [PolymerElements/app-layout#306]
### Description
begining with 0.10.2, if app-drawer contains iron-collapse, when iron-collapse is toggled, app-drawer closes
### Expected outcome

app-drawer does not close when iron-collapse in drawer toggled

### Actual outcome

app-drawer closes

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@undermensch I can't seem to reproduce this in Chrome - http://jsbin.com/yodoricobi/edit?html,output

**Comment by keanulee** [comment]
@undermensch Ah, the issue was with `app-drawer-layout` which we recently fixed in #278. We just released v0.10.3 which should fix this.
