### ISSUE TITLE
FEATURE REQUEST: <app-box> Preloading Images?

### ISSUE THREAD

**Issue by oneezy** [PolymerElements/app-layout#311]
The [Shop App](https://github.com/Polymer/shop) out of the box is packaged with a `<shop-image>` element that pre-loads base64 images and then fades in a high resolution image when it's ready to avoid the dreaded FOUC (I think this idea was brilliant! Shout out to whoever thought of that).

I think the `<app-box>` should have this functionality as well. How could we implement this behavior within it?

-----

**Shop Image:**
```
    <shop-image
        alt="[[category.title]]"
        src="[[category.image]]"
        placeholder-img="[[category.placeholder]]" class="hero-image"></shop-image>
```

**Comment by frankiefu** [comment]
`<app-box>` allows you to put the image in the light DOM, e.g.
```
<app-box effects="parallax-background">
  <img background src="bg1.jpg">
</app-box>
```
So you could just put any elements e.g. `<iron-image>` or `<shop-image>`, that have logic to do loading effect in the light DOM of `<app-box>`

**Comment by oneezy** [comment]
@frankiefu , thanks! That's actually exactly what I did
