### ISSUE TITLE
Multiple app-grid in the local DOM of an element

### ISSUE THREAD

**Issue by timeu** [PolymerElements/app-layout#315]
I was wondering if it is possible to have multiple `app-grid` with different custom CSS properties/configurations. 

I tried something along the these lines: 

```html
<dom-module id="thg-start">
    <style include="app-grid-style">
        :host {
           --app-grid-columns: 4;
        }
        .custom-grid {
            --app-grid-columns: 2;
        }
   </style>
   <template>
       <ul class="app-grid">
            <li>Col1/4</li>
            <li>Col2/4</li>
            <li>Col3/4</li>
            <li>Col4/4</li>
       </ul>
      <ul class="app-grid custom-grid">
          <li>Col1/2</li>
          <li>Col2/2</li>          
     </ul>
  </template>
</dom-module>
```

But it didn't work. Basically only `custom-grid` inherits the configuration that is defined in `:host`
I am not sure if this is a limitation of the styling system of Polymer or a user error or a limitation of `app-grid`

**Comment by frankiefu** [comment]
Yes, this is a [limitation of Custom properties in Polymer](https://www.polymer-project.org/1.0/docs/devguide/styling#custom-properties-shim-limitations).  Basically within a given element's local DOM scope, a custom property can only have a single value.

**Comment by JosefJezek** [comment]
@timeu I created `s-grid` allowing nested grids https://www.webcomponents.org/element/StartPolymer/s-grid

**Comment by Matheus-Ribeiro95** [comment]
Nice Josef Jezek, thank you!!!!!!!!
