### ISSUE TITLE
Responsive app-header with background

### ISSUE THREAD

**Issue by rebeccamarye** [PolymerElements/app-layout#326]
It appears that in order to display a background image in an app-header you have to set an explicit height. At any rate, the demos do so, and none of my experiments with any other css result in the correct behavior. But a fixed-height app-header isn't responsive -- my header is 400px high even on a mobile.

Here's the relevant sections of my css & code (based on the contacts demo)

            app-header {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                height: 400px;
                color: #fff;
                background-color: var(--primary-color);
                --app-header-background-front-layer: 
                {
                    background-image: url(../images/RaggedyBanner.png);
                    background-size: contain;
                    background-repeat: no-repeat;
                }
            }

and the html:

        <app-header-layout>
            <app-header effects="waterfall resize-title blend-background parallax-background" fixed condenses>
                <app-toolbar>
                    <div condensed-title>Raggedy Edge Designs</div>
                </app-toolbar>
                <app-toolbar>
                    <div main-title></div>
                </app-toolbar>
            </app-header>
        </app-header-layout>

Is there a different way to achieve what I need, or is this an issue with the app-header?

**Comment by frankiefu** [comment]
You can use media query to change the height of `app-header`, e.g.
```
    /* mobile */
    @media (max-width: 639px) {
      app-header {
        height: 200px;
      }
    }
```

**Comment by rebeccamarye** [comment]
I was afraid of that, thanks. It would be nice if we could use a mix-in here (so I could use <picture> or even <srcset>

**Comment by rebeccamarye** [comment]
Just an update in case anybody else runs into this issue. This works:

            app-header {
                position: fixed;
                top: 0;
                left: 0;
                width: 100%;
                padding-bottom: 35%;
                color: #fff;
                background-color: var(--primary-color);
                --app-header-background-front-layer:

            {
                background-image: url(...whatever...);
                background-repeat: no-repeat;
                background-position: center;
                background-size: contain;
            }

Theoretically, padding-bottom should be set to the base aspect-ratio (width/height), but I had to fiddle with it a bit.

**Comment by jobizzness** [comment]
Hi everyone! Is it possible to bind to the background image and have it change on different routes ?

**Comment by dshukertjr** [comment]
There actually is!

So, first you create an css variable: 
``` 
     :host {
        --header-image: url(<url of default image>);
      }
```

Then inside your script tag, fire a method something like this: 
```
        if(this.page == "questions") { 
          this.customStyle['--header-image'] = 'url(<image url>)';
          this.updateStyles();
        }else if(this.page == "post"){
          this.customStyle['--header-image'] = 'url(<different image url>)';
          this.updateStyles();
        }else{
          this.customStyle['--header-image'] = 'url(<other image url>)';
          this.updateStyles();
        }
```

I know I should use switch instead of if's, I know I'm a bad programmer, but you get the idea
