### ISSUE TITLE
Bug: app-drawer glitches while shell is loading

### ISSUE THREAD

**Issue by AlexAlabyev** [PolymerElements/app-layout#341]
### Description
I'm using polymer starter kit 2.0 (4 template) 

`App-drawer` glitches while shell is loading. It opens for like 0.2 second and closes right away.

You can clearly see this glitch in the EDGE and Firefox (sometimes)

### Code
```

<app-drawer-layout fullbleed force-narrow>
<app-drawer swipe-open opened="{{drawerOpened}}">
   ...
</app-drawer>

```
Maybe `force-narrow` is what causing the problem?
### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by AlexAlabyev** [comment]
For some silly reason I managed to fix this by adding `style="visibility:hidden;"` like that:

      <app-drawer swipe-open opened="{{drawerOpened}}"  style="visibility:hidden;">

If someone find a better solution, please let us know here. But the drawer behave as it should now. 
@valdrinkoshi @robdodson

**Comment by keanulee** [comment]
@AlexAlabyev I couldn't replicate this with Firefox/Edge. Can you delete your `bower_components` directory and run `bower install` again?

**Comment by AlexAlabyev** [comment]
@keanulee thank you for the answer. I just found what is causing the problem. It's this code:
```
 // closing drawer after changing a page
 _routePageChanged: function(page) {
       this.page = page || 'home';
      // Scroll to the top of the page on every *route* change. Use `Polymer.AppLayout.scroll`
      // with `behavior: 'silent'` to disable header scroll effects during the scroll.
     Polymer.AppLayout.scroll({ top: 0, behavior: 'silent' });
     // Close the drawer - in case the *route* change came from a link in the drawer.
     this.drawerOpened = false;
 },
```
 I added this code inside the `script` tag on the bottom of **my-app.html** page:
 

```
  <script>
    Polymer({
      is: 'my-app',
      ...
      // HERE
  });
  <script>

```

I added it because I wanted the drawer to get closed whenever I change a page there. 

Could you please tell me how can I achieve that in the polymer starter kit 2.0 ? 

It works in the previous starter kit version. So I took that code from there, it works in the psk 2.0 too but it's causing this problem and I have no idea how to fix that. Do I need to put it in a separate `script` tag below that `polymer {{ }}` script ? 
Could you please show me with the code to achieve that?
