### ISSUE TITLE
app-header crashes chrome tab on default <slot> element

### ISSUE THREAD

**Issue by GijsWeterings** [PolymerElements/app-layout#345]
### Description
While using the `app-header` element on the `2.0-preview` branch, the entire chrome tab will completely crash (as in, dead dead). This is due to a bug with the default slot.
### Expected outcome
The app-header works as expected.

### Actual outcome
The tab crashes without error or explaination, asking to send a crash report to the chrome team.

### Live Demo
I can't give you an actual jsbin, because the tab would instantly crash. A code example to trigger this error:
```
<!doctype html>
<html>
<head>
  
  <meta charset="utf-8">

  <base href="//polygit.org/custom-elements+webcomponents+:master/polymer+polymer+:2.0-preview/app-layout+polymerelements+:2.0-preview/components/">

  <script src="custom-elements/custom-elements.min.js"></script>

  <link href="polymer/polymer.html" rel="import">
  <link href="app-layout/app-header/app-header.html" rel="import">

</head>
<body>
  
  <app-header>
    This is crashing
  </app-header>
  
</body>
</html>
```
### Steps to reproduce
1. Use the 2.0-preview branch of app-layout
2. use the app-header element in your app
3. watch it burn.

### Steps to un-crash
1. Modify the app-header code, giving the `<slot>` a proper name (such as `<slot id="slot" name="header"></slot>`)
2. Allow the content to flow to that slot by scoping the child content to `slot="header"`

However, I believe this might be an underlying issue. I tried it with app-box, but that somehow did not crash... No idea why

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by frankiefu** [comment]
Chrome 53 doesn't has the Shadow DOM API `getRootNode` so Polymer defaults to use ShadyDOM there. In your jsbin if you include loading `shadydom.min.js` and `shadycss.min.js` then it should work. We are still ironing out all the details of the polyfills. For now if you want to test `app-layout` `2.0-preview` elements I'd suggest to load `webcomponents-lite.js`.
