### ISSUE TITLE
app-grid: infer columns

### ISSUE THREAD

**Issue by mbana** [PolymerElements/app-layout#348]
Is there a reason why you simply can't infer the columns instead of defaulting to one? Sometimes, one doesn't know ahead-of-time the count of the columns. I would imagine something like the below working since bindings,  `[[gridColumnCount]]`, are supported with `<template>` and nesting a `<style>` within it will achieve what I am after?

Either that, or please provide an example of `--app-grid-columns` having a dynamic value.

```javascript
<template>
  <style include="app-grid-style">

    :host {
      --app-grid-columns: [[gridColumnCount]];
      --app-grid-item-height: 100px;
    }

    ul {
      padding: 0;
      list-style: none;
    }

    .item {
      background-color: white;
    }

    @media (max-width: 640px) {
      :host {
        --app-grid-columns: [[gridColumnCount]];
      }
    }

  </style>
  <ul class="app-grid">
    <li class="item">1</li>
    <li class="item">2</li>
    <li class="item">3</li>
  </ul>
</template>
```

**Comment by blasten** [comment]
That would require to know the size of the grid items upfront, but if that is the case why would you need app-grid? You could just do this: http://jsbin.com/femoma/edit?html,output
