### ISSUE TITLE
Scroll bar and toolbar are visible when you open YouTube video fullscreen

### ISSUE THREAD

**Issue by AlexAlabyev** [PolymerElements/app-layout#353]
### Description

I'm using polymer starter kit 2.0 

When I embed a YouTube video on one of the `<iron-pages>` views and then click full screen, the toolbar and  the page's scroll bar are visible (in Chrome)

Is that a known issue? Google search didn't show anything about it.

**Comment by keanulee** [comment]
I suspect that it's related to this since we use `will-change` in app-header: https://bugs.chromium.org/p/chromium/issues/detail?id=582318

**Comment by blasten** [comment]
The chrome bug is reported as fixed. I can't repro the issue in http://output.jsbin.com/wimura anymore.

**Comment by bennypowers** [comment]
I still have this issue. see evebot.io
