### ISSUE TITLE
Can i have persistent + scrim together in app-layout ?

### ISSUE THREAD

**Issue by sp1rs** [PolymerElements/app-layout#355]
### Description

Can i have persistent + scrim together in app-layout  similar to draggable in paper-drawer-panel ?

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
Sounds like you want a way to disable swipe to open/close the drawer.  Similar to [disableSwipe](https://github.com/PolymerElements/paper-drawer-panel/blob/master/paper-drawer-panel.html#L382) in `paper-drawer-panel`.  @keanulee wdyt?
