### ISSUE TITLE
Scroll effects using protected `_warn` method not compatible with Closure compiler

### ISSUE THREAD

**Issue by keanulee** [PolymerElements/app-layout#369]
Some scroll effects are using the protected `this._warn` method defined by Polymer, which causes Closure warnings. We should use the native `console.warn` method instead

Example:
https://github.com/PolymerElements/app-layout/blob/master/app-scroll-effects/effects/resize-title.html#L32

cc @frankiefu @blasten

**Comment by frankiefu** [comment]
Sounds good.  FWIW, we changed to use `console.warn` in `2.0-preview` branch: https://github.com/PolymerElements/app-layout/commit/b42f214333b85bde4bcc7610423816a7394b5aff#diff-d31bb78c261ac020cb38c93dc22ca18aL280
