### ISSUE TITLE
Feature Request: Emulate Colspan with Expandible Items

### ISSUE THREAD

**Issue by bennypowers** [PolymerElements/app-layout#373]
### Who will use the feature?
Users who wish to create complex table layouts such as this: 
<table>
  <tr>
    <td>1</td>
    <td>1</td>
    <td>1</td>
    <td>1</td>
    <td>1</td>
    <td>1</td>
  </tr>
  <tr>
    <td colspan="2">2</td>
    <td colspan="2">2</td>
    <td colspan="2">2</td>
  </tr>
  <tr>
    <td>1</td>
    <td colspan="5">5</td>
  </tr>
</table>

### When will they use the feature?
In any case where a user wants to create a complex responsive table layout

### What is the user’s goal?
Use app-grid to create a complex table layout

## Potential implementation
    <style include="shared-styles app-grid-style">
    :host {--app-grid-columns: 6;}
    .colspan2 {--app-grid-expandible-item-columns: 2;}
    .colspan3 {--app-grid-expandible-item-columns: 3;}
    .colspan4 {--app-grid-expandible-item-columns: 4;}
    .colspan5 {--app-grid-expandible-item-columns: 5;}
    .colspan6 {--app-grid-expandible-item-columns: 6;}
    .expanded {@apply(-app-grid-expandible-item);}
    </style>
    <div class="app-grid">
      <div>1</div>
      <div>1</div>
      <div>1</div>
      <div>1</div>
      <div>1</div>
      <div>1</div>
      <div class="colspan2">
        <div class="expanded">2</div>
        <div class="expanded">2</div>
        <div class="expanded">2</div>
      </div>
      <div class="colspan5">
        <div>1</div>
        <div class="expanded">5</div>
      </div>
    </div>

**Comment by blasten** [comment]
This a limitation of the custom property shim, so it's unlikely that this behavior would be supported until most browsers support native custom properties. You can still try this [vanilla version](http://output.jsbin.com/vucirix) which should cover this use case.

**Comment by guiomie** [comment]
What would be the recommended way to emulate Colspan in Polymer 3? Having only one possible type of expandable column is really limiting.

**Comment by bennypowers** [comment]
@guiomie Can you use css grid?

**Comment by keanulee** [comment]
Consider using [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout) (or tables for [legacy browser support](https://caniuse.com/#feat=css-grid)) instead of app-grid for this use case.
