### ISSUE TITLE
app-header larger then app-header-layout

### ISSUE THREAD

**Issue by AlexNasonov** [PolymerElements/app-layout#377]
### Description
On page load <app-header> width is set to 100% of page, that makes it partly hide behind the drawer on high resolution. Actually it becomes wider then its app-header-layout parent. App-header width goes normal after window resize.

### Browsers Affected
- [x ] Chrome
- [x ] Edge
- [x ] IE 11

**Comment by frankiefu** [comment]
This may have been fixed in https://github.com/PolymerElements/app-layout/pull/322.  Please verify with the latest release (v0.10.6).

**Comment by frankiefu** [comment]
Closing this, please reopen if the issue still exists.
