### ISSUE TITLE
app-header didn't render correctlyin firefox

### ISSUE THREAD

**Issue by 3mp3ri0r** [PolymerElements/app-layout#378]
### Description

Header didn't render correcty in firefox 49.0.2 on linux. Title didn't render when in desktop mode. The header start render in the right corner when change from desktop mode to mobile mode.

### Actual outcome

![screenshot from 2016-11-10 00-50-53](https://cloud.githubusercontent.com/assets/3140815/20148928/7e0fd45a-a6e1-11e6-9c86-11220c5f5d76.png)
![screenshot from 2016-11-10 00-51-00](https://cloud.githubusercontent.com/assets/3140815/20148937/867b5e84-a6e1-11e6-924c-0e2d44c2503b.png)

### Code
```
<link rel="import" href="../../bower_components/polymer/polymer.html">
<link rel="import" href="../../bower_components/paper-icon-button/paper-icon-button.html">
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../../bower_components/app-layout/app-layout.html">
<link rel="import" href="../../bower_components/app-layout/app-scroll-effects/app-scroll-effects.html">


<dom-module id="hello-app">
  <template>
    <style>
      :host {
        display: block;
      }
      app-header {
        background-color: red;
        --app-header-background-rear-layer: {
          /* The header is blue when condensed */
          background-color: blue;
        };
      }
    </style>
  

  <app-drawer-layout>

    <app-drawer>
      <app-toolbar>Getting Started</app-toolbar>
    </app-drawer>

    <app-header-layout>

      <app-header reveals effects="waterfall">
        <app-toolbar>
          <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
          <div main-title>Title</div>
        </app-toolbar>
      </app-header>

      <div>Content goes here</div>

    </app-header-layout>

  </app-drawer-layout>
  </template>

  <script>
    Polymer({

      is: 'hello-app',

    });
  </script>
</dom-module>

```

### Browsers Affected

- [ ] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
Fixed in https://github.com/PolymerElements/app-layout/pull/322

**Comment by 3mp3ri0r** [comment]
Hi @frankiefu. I've install the latest version of app-layout (v 0.10.5). Is it not merged to published version yet?

**Comment by frankiefu** [comment]
@3mp3ri0r The latest release is [v0.10.6](https://github.com/PolymerElements/app-layout/releases/tag/v0.10.6) which should contain the fix for this issue.
