### ISSUE TITLE
app-drawer rendered differently in firefox and chrome.

### ISSUE THREAD

**Issue by 3mp3ri0r** [PolymerElements/app-layout#379]
### Description
app-drawer rendered differently in firefox and chrome.

### Actual outcome
For Chrome:
![screenshot from 2016-11-11 13-10-08](https://cloud.githubusercontent.com/assets/3140815/20206048/73ca9536-a810-11e6-9703-d24727c30774.png)

For Firefox:
![screenshot from 2016-11-11 13-10-21](https://cloud.githubusercontent.com/assets/3140815/20206050/7753ac92-a810-11e6-97c9-0a52b5a6551e.png)

### Code
https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/demo/two-drawers.html

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@3mp3ri0r Do you have a code reproduction of what you're doing? That is not what I see with the two-drawers demo:

![image](https://cloud.githubusercontent.com/assets/1319720/20280531/ad203d88-aa61-11e6-9514-c980a61cd0c7.png)

**Comment by 3mp3ri0r** [comment]
@keanulee: I used code from github actually with a little bit modifying so it can be used in polymer project. I don't get that problem now (rendered differently on firefox) and I don't know why.
