### ISSUE TITLE
make footer syllable independently of other content

### ISSUE THREAD

**Issue by davidmaxwaterman** [PolymerElements/app-layout#383]
### Description
app-header-layout swallows all light dom other than app-header into div#contentContainer, and it is impossible to style. Perhaps a generic mixing could allow the user to style light dom elements independently.
My use-case is I have a iron-pages and footer element, and both of those are placed into the contentContainer - actually that isn't ideal in itself since footer is a peer of {app-}header so isn't content. This is per the 'footer' example in app-header-layout documentation. I want the width of the footer to fit the app-header-layout, like the app-header does, but I don't want the iron-pages to fit; but I can't style them independently.

A mixin on the #contentContainer might help since it should then have width:100% to fill the host, and then the actual content could have width set to 50% or something. 

### Expected outcome
footer is same width as app-header

### Actual outcome
footer is same width as other contentContainer content - not possible to set width to 100% (which looks like it would be the app-header-layout width since that is the apparent parent), and it is necessary to set a specific width (eg width:1300px).

### Steps to reproduce
1. Go to https://elements.polymer-project.org/elements/app-layout?view=demo:app-header-layout/demo/footer.html&active=app-header-layout
2. try to make (keep) footer at width of apparent (ie outside shadow dom) parent ie `app-layout-header` not `#contentContainer`, while reducing the width of the content

**Comment by keanulee** [comment]
To put the footer on the same level as `app-header`, consider using `app-header` on its own without using `app-header-layout`. `app-header-layout` is designed to layout a header and simple content, but you can use it as a starting point for something more custom.

**Comment by davidmaxwaterman** [comment]
@keanulee ok, but when I look at `app-header` docs, the first line is :

> app-header is container element for app-toolbars at the top of the screen that can have scroll effects

...and I don't want that at all (ie I don't want any scroll effects). That, combined with the 'footer' demo on `app-header-layout` lead a user along the path I took.

Perhaps the `footer` demo on `app-header-layout` should be moved to `app-header` if it is more appropriate, or at least one should be added?

**Comment by davidmaxwaterman** [comment]
while this issue is probably still valid, I'm wondering if my actual requirements are even simpler ... I actually don't want any scrolling other than provided by the browser, and the header and footer are always scrolled along with the main content - ie it's quite a traditional web site behaviour. What layout do you recommend for this simple use-case?

**Comment by keanulee** [comment]
If all you need is a simple header/footer layout that scrolls with content, you should consider just using plain HTML elements. Here's an example: http://jsbin.com/qufecu/edit?html,output. Most of the value that `<app-header>` provides is scroll effects, so it's not really necessary if you don't need those.

**Comment by davidmaxwaterman** [comment]
Hrm, thanks for that. It's fair enough, I suppose, but I do somehow find it disappointing that it doesn't handle the simple case, and so allow easy migration to more interesting behaviours; but yeah, perhaps that's just because I've put the effort into making app-layout do what I want and almost gotten there.

**Comment by davidmaxwaterman** [comment]
Actually, on reflection, this kind of fits with Polymer's more general motivation of not replicating things that are already in the platform - your example shows how the objective is easily obtained using plain HTML elements and having implemented it that way, it is quite a lot nicer. Thanks.
