### ISSUE TITLE
can close persistent drawer

### ISSUE THREAD

**Issue by robrez** [PolymerElements/app-layout#384]
### Description
It is possible to close a persistent drawer. This results in a blank region (in a drawer-layout) where the persistent drawer should be. I've attempted to close a drawer whenever the route changes. I've added a sanity check should, debatably, exist within the drawer component itself

```
        var appDrawer = this.$.appDrawer;
        if (!appDrawer.persistent) {
          appDrawer.opened = false;
        }
```

### Expected outcome
Persistent drawers should not close

### Actual outcome
Persistent drawers close

![drawerbug](https://cloud.githubusercontent.com/assets/1993389/20678406/363b4108-b55c-11e6-94f9-cff3f3f68239.jpg)

### Live Demo
https://jsbin.com/quvozubopu/edit?html,output

### Steps to reproduce
1. Create an app-drawer-layout
2. When the app-drawer is in persistent mode (either via default responsive behavior or declaratively), call `close()` or set `opened = false` on the drawer element

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
`app-drawer-layout` is designed to handle the opened state of the drawer, so if you want to toggle the state of the drawer, consider changing `forceNarrow` on `app-drawer-layout` rather than manipulating the state of the drawer itself. For something more custom, consider using `app-drawer` on its own.

**Comment by robrez** [comment]
Thanks for the feedback. For future consumers who expected the drawer to "just work", here are a couple of other examples (demo templates) that are using the same technique I deployed:
- zuperkulblog
https://github.com/PolymerElements/app-layout/blob/master/templates/publishing/src/blog-app.html#L323-L325
- pesto
https://github.com/PolymerElements/app-layout/blob/master/templates/pesto/src/recipe-app.html#L202-L204
