### ISSUE TITLE
Please make `persistent` notify:true

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/app-layout#385]
Hi,

I have an application that will display (or not display) the menu button depending on the drawer being persistent or not.
At the moment, `persistent` in `app-drawer` doesn't notify. So... well, there is no solution or hack I can think of that will make things work.

I don't suppose you could please make `persistent` `notify:true`, so that I can actually get this finished?

Any good reason why it doesn't notify?

Thank you!

Merc.

**Comment by mercmobily** [comment]
Right now I am "resolving" it with this:

        /* MONKEY PATCH app-drawer, IMPLEMENTS:
          https://github.com/PolymerElements/app-layout/issues/385
        */
        var e = document.createElement('app-drawer');
        var p = Object.getPrototypeOf( e );
        p._openedPersistentChanged = function(){
          if (this.transitionDuration === 0) {
            // Reset drawer state now since there will be no transitionend event.
            this._resetDrawerState();
          }
          this.fire('persistent-changed', { bubbles: true } );
        }

But it's "kind of"... err.. "less than ideal"!

**Comment by keanulee** [comment]
@mercmobily What is changing `<app-drawer>`'s `persistent` property? If you're using `<app-drawer-layout>`, you can just use that element's `narrow` property (which is notifying). Otherwise, some other piece of code is changing the `persistent` property, so you can add some notification from there. (`notify` adds a performance cost since it fires an event, so I'm trying to see if it's really necessary.)

**Comment by mercmobily** [comment]
> What is changing <app-drawer>'s persistent property? I

Well, me switching to mobile view or non-mobile view. Or me zooming in with CTRL+ till the estate becomes rare...

>  If you're using <app-drawer-layout>, you can just use that element's narrow property (which is notifying). 

Yep, Wasn't aware of that one -- fantastic!

> Otherwise, some other piece of code is changing the persistent property, so you can add some notification from there. (notify adds a performance cost since it fires an event, so I'm trying to see if it's really necessary.)

Nope, it's Polymer itself, but I have tested it with using `narrow` and it works great -- thank you!

I have this:

      <app-drawer-layout narrow="{{siteInfo.drawerPersistent}}" fullbleed responsive-width="1040px">

And I have `siteInfo` as a notifying property. So, I should be all good -- thank you!

Merc
