### ISSUE TITLE
Dynamic header with iron-pages have bug in app-drawers-layout

### ISSUE THREAD

**Issue by 3mp3ri0r** [PolymerElements/app-layout#386]
### Description
Hi all, it's good to use iron-pages to make dynamic header, but I've got some problem. Strange behavior happen when I use app-drawer-layout and in mobile mode (which mean the drawer is hidden). When I open the drawer and open some link from that drawer, the page that I click is opened but I can't scroll that page. After that, I press back button and back to home page, I still can't scroll the page. I can scroll home page again after I open the drawer and close it. Which mean, I can't scroll the other page that open from drawer.

### Expected outcome

I can scroll every page although I open it from drawer.

### Actual outcome

I can't scroll page that opened from drawer

### Steps to reproduce

1. Open home page that header and content load from iron-pages in mobile mode
2. Open drawer and open some pages from drawer.
3. Try to scroll that page (you won't be able to scroll)
4. Press back button so you open back the home page
5. Try to scroll that page (you won't be able to scroll)
6. Open drawer and closed it
7. Try to scroll that home page (you can scroll it now)

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
`app-drawer` disables page scrolling when the drawer is opened and re-enables it when it is closed (by setting `body { overflow: hidden }`. If `app-drawer` is hidden while it is opened (e.g. by making the page it's in not selected by `iron-pages`), then it won't re-enable scrolling again. Usually, app-drawer is in the top-level of the DOM structure (e.g. not in `iron-pages`) so it's always visible while opened, but in this case you may have to manually close the drawer after clicking the link.

**Comment by 3mp3ri0r** [comment]
Hi @keanulee. I got what you said. How can I manually close the drawer when in other pages I didn't use app-drawer?

**Comment by keanulee** [comment]
You can set its `opened` property to false (e.g. `document.querySelector('app-drawer').opened = false`)

**Comment by 3mp3ri0r** [comment]
I've observed the selected-atribut in iron-pages so when home page is hidden by iron-pages, I closed the drawer. I've successfully closed the drawer, but I still can't scroll in other page. Any other suggestion, @keanulee?

**Comment by 3mp3ri0r** [comment]
I've solved this issue. Instead closed the drawer, I just change the overflow value in the body tag. I do this by checking is the home page appear using iron-pages selected-attribute. This is the sample code.
```
//Properties
appearance: {
  type: Boolean,
  observer: '_overflowToggle',
}

```
```
//Function
_overflowToggle: function() {
  if (!this.tampil) {
    if(document.querySelector('app-drawer').opened){
      document.querySelector('body').style.overflow = 'auto';
    }
  }
  else {
    if(document.querySelector('app-drawer').opened){
      document.querySelector('body').style.overflow = 'hidden';
    }
  }
},
```
