### ISSUE TITLE
app-box #background element has incorrect z-index relative to paper-drawer

### ISSUE THREAD

**Issue by mhorman** [PolymerElements/app-layout#389]
### Description
When a drawer is opened over an app-box element with parallax effect the #background div is positioned over the drawer which is incorrect according to material design.

Could be due to the use of transform: translate3d on the #backgroundFrontLayer which has known issues with z-index positioning.

### Expected outcome
When drawer is visible, drawer is position over the entire page content.

### Actual outcome
The parallax background sits over the drawer

### Live Demo
https://jsfiddle.net/mhorman/ehrv7jbw/1/

### Steps to reproduce

1. Edit the app-box scrolling region demo
2. Add an app-header
3. Within the app-header add an app-toolbar
4. Within the app-toolbar add <paper-icon-button icon="menu" onclick="drawer.toggle()"></paper-icon-button>
5. Below app-header add app-drawer (e.g. <app-drawer id="drawer" swipe-open></app-drawer>)
6. Run and open the drawer

### Browsers Affected
- Only tested in Chrome

**Comment by blasten** [comment]
Your css is missing a z-index for the app-drawer:

```css
app-drawer {
  z-index: 1;
}
```
