### ISSUE TITLE
app-grid-style does not style distributed children

### ISSUE THREAD

**Issue by ahaasler** [PolymerElements/app-layout#394]
### Description
The `app-grid-style` helper doesn't work if the desired items are specified as template content (distributed children).

### Expected outcome
The grid works with distributed children.

### Actual outcome
The grid does not recognize items that are distributed children.

### Live Demo
https://jsbin.com/sapenu/edit?html,output

### Steps to reproduce
1. Define an app-grid custom module that does not define it's elements in the template, and rather uses the content tag.
  ```html
<dom-module id="colos-grid">
  <template>
    <style include="app-grid-style">

      :host ::content {
        display: block;
        --app-grid-columns: 2;
        --app-grid-gutter: 1px;
        --app-grid-expandible-item-columns: 2;
      }

      :host ::content .item {
        background-color: #eee;
      }

      :host ::content .expandible-item {
          @apply(--app-grid-expandible-item);
      }

      @media (max-width: 799px) {
        :host ::content {
          --app-grid-columns: 1;
          --app-grid-gutter: 1px;
          --app-grid-expandible-item-columns: 1;
        }
      }

    </style>
    <content></content>
  </template>
  <script>
    HTMLImports.whenReady(function() {
      Polymer({
        is: 'colos-grid',
        attached: function() {
          this._updateGridStyles = this._updateGridStyles || function() {
            this.updateStyles();
          }.bind(this);
          window.addEventListener('resize', this._updateGridStyles);
        },
        detached: function() {
          window.removeEventListener('resize', this._updateGridStyles);
        }
      });
    });
  </script>
</dom-module>
  ```

2. Use it like this:
  ```html
<colos-grid>
  <div class="app-grid">
    <div class="item">Lorem ipsum dolor sit amet</div>
    <div class="item">consectetur adipiscing elit</div>
    <div class="item expandible-item">Donec a ante sapien. Aenean facilisis urna est, id ornare lorem luctus id. Vivamus vel dui vitae est sagittis viverra in fringilla nisl.</div>
  </div>
</colos-grid>
  ```

3. Check it

### Browsers Affected
Only tested on Chrome, Opera and Firefox, but should affect all.
- [x] Chrome
- [X] Firefox
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

### Resolution

I've already fixed it adding `::content` to the styles like you can see in this commit: ahaasler/app-layout@f9d77a5e32cb9143dec83b59a9b571ff9ea20fb7. It's not currently in a PR following contribution guidelines:
> The goal is to discuss the design and necessity of the proposed change with Polymer authors and community before diving into a pull request.

**Comment by andrewebdev** [comment]
:+1:  Ran into same issue and was considering logging a issue and creating a PR myself, then saw you already did

**Comment by ahaasler** [comment]
Should I wait a little bit more so owners/contributors can answer to this issue or do I create the PR directly?

**Comment by andrewebdev** [comment]
Just have a quick read through their contribution guidelines and make sure that all is well tested on your side, and you should be ok to just create a PR.

With that said, I'm wondering if they are holding off on changes until they've finished V2

**Comment by blasten** [comment]
It would be great to support that. Feel free to send a PR against `0.x`
