### ISSUE TITLE
Attribute FIXED seems not working in branch 2.0-preview

### ISSUE THREAD

**Issue by altus34** [PolymerElements/app-layout#403]
### Description
Attribute **fixed** in app-header seems not working in **2.0-preview** branch.

### Expected outcome

app-header should be fixed if the attribute is here

### Actual outcome

app-header is never fixable

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by altus34** [comment]
It's working, my bad ;(

**Comment by altus34** [comment]
No, in fact I can reproduce.
So working well in v0.10.6 and issue in 2.0-preview

**Comment by frankiefu** [comment]
@altus34 The demo `app-layout/app-header/demo/custom-sticky-element-1.html` which has `fixed` on `<app-header>` and it seems to work fine.  Can you provide a testcase/jsbin showing the issue?

**Comment by altus34** [comment]
Yes it's working I've used the CSS: @apply(--layout-fixed-top) but in the example a position: fixed; is used.

Thanks.
