### ISSUE TITLE
Manually condensing the header in app-header-layout

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#404]
There was an easy way to condense header in <code>paper-scroll-header-panel</code>:

<pre><code>var scrollTop = this.$.scrollPanel.headerHeight - this.$.scrollPanel.condensedHeaderHeight;
if (this.$.scrollPanel.headerState != Polymer.PaperScrollHeaderPanel.HEADER_STATE_CONDENSED)
	this.$.scrollPanel.scroller.scrollTop = scrollTop;</code></pre>

What would be the right way to do it with <code>app-header-layout</code>? I tried setting <code>header.scrollTarget.scrollTop</code>, but it doesn't seem to be working. Adding properties to access header state and height(s) as above might be useful as well.

**Comment by blasten** [comment]
You can call the `scroll` method on app-header:
```js
appHeader.scroll(0, SCROLL_POSITION);
```
The `SCROLL_POSITION` will need to be computed manually because the `app-header` doesn't expose `appHeader._dHeight` which is the scroll position to condense the header.

**Comment by govis** [comment]
Thank you, I'll give it a try.

**Comment by govis** [comment]
<code>appHeader.scroll(0, SCROLL_POSITION);</code> has been working for some time, but now <code>app-layout</code> seems to be overriding it:

http://jsbin.com/bimefoquza/edit?html,console,output

Any idea on what's changed or how can I make it stick?
