### ISSUE TITLE
Incorrect content position in app-header-layout

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#406]
### Description
app-header-layout (with has-scrolling-region + fixed + condenses) - the content is not positioned properly until window is manually resized.

Might be related to https://github.com/PolymerElements/app-layout/issues/320

There appear to be even more(severe) layout issues if content is loaded dynamically and/or elements are upgraded lazily with importHref.

### Expected outcome

![image](https://cloud.githubusercontent.com/assets/971651/22471307/f530fa10-e79f-11e6-87b8-350af600ed2c.png)

### Actual outcome

![image](https://cloud.githubusercontent.com/assets/971651/22471264/e1bde4ca-e79f-11e6-9d99-def72f8f4688.png)

![image](https://cloud.githubusercontent.com/assets/971651/22471286/ea8aded2-e79f-11e6-866c-6d5c1ec020a3.png)

### Live Demo
<pre><code>
    &lt;link rel="import" href="../../polymer/polymer.html">
    &lt;link rel="import" href="../../app-header/app-header.html">
    &lt;link rel="import" href="../../app-toolbar/app-toolbar.html">
    &lt;link rel="import" href="../app-header-layout.html">
    &lt;link rel="import" href="../../demo/sample-content.html">

    &lt;dom-module id="simple-layout">
        &lt;template>
            &lt;style>
                  app-header {
                    background-color: #4285f4;
                    color: #fff;
                  }
            &lt;/style>
            &lt;app-header-layout fullbleed has-scrolling-region>
                &lt;app-header slot="header" fixed condenses>
                    &lt;app-toolbar style="height:128px;">&lt;/app-toolbar>
                    &lt;app-toolbar sticky>
                        &lt;div spacer main-title>My Drive&lt;/div>
                    &lt;/app-toolbar>
                &lt;/app-header>
                &lt;sample-content size="100">&lt;/sample-content>
            &lt;/app-header-layout>
        &lt;/template>
        &lt;script>
            Polymer({
                is: 'simple-layout'
            });
      &lt;/script>
    &lt;/dom-module>
<code></pre>

### Steps to reproduce

Run the above code against the latest #2.0-preview branch using the in latest Chrome browser

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by govis** [comment]
It seems that Fix #320 hasn't made it's way into the 2.0-preview branch yet and by skimming through the master branch I can see that it now uses IronResizableBehavior whereas 2.0-preview does not. Interestingly some other fixes (#340) are made in the 2.0-preview and there've been commits, so it seems active yet out of date.

**Comment by frankiefu** [comment]
@govis I verified this is a bug.  Thanks for the report.

**Comment by frankiefu** [comment]
This should be fixed in the latest `2.0-preview` branch
