### ISSUE TITLE
app-drawer-layout inside app-header-layout

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#407]
### Description
In the doc you provide an example of an app-header-layout inside app-drawer-layout: https://github.com/PolymerElements/app-layout/tree/master/app-drawer-layout

I think the reverse order (app-drawer-layout inside app-header-layout) might be a common scenario as well. Unfortunately it doesn't work as app-drawer currently overlaps app-header due to the fixed positioning. I think it should be absolute, so it can fit inside the relatively positioned content of app-header-layout. This used to work when paper-drawer-panel is inside paper-header-panel, but not in app-layout.

### Expected outcome

app-drawer to be stacked below app-header

### Actual outcome

![image](https://cloud.githubusercontent.com/assets/971651/22522661/7140544e-e88a-11e6-9df3-36583bf35e4d.png)

### Live Demo

<pre><code>
&lt;app-header-layout>
    &lt;app-header>
        &lt;app-toolbar>
            &lt;div main-title>App name&lt;/div>
        &lt;/app-toolbar>
    &lt;/app-header>

    &lt;app-drawer-layout>
        &lt;app-drawer slot="drawer">
            drawer-content
        &lt;/app-drawer>
        main-content
    &lt;/app-drawer-layout>
&lt;/app-header-layout>
</code></pre>

### Steps to reproduce

Replace the app-layout/app-drawer-layout/demo/index.html with the content above, run the sample. I tried it with 2.0-preview branch.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@govis `position: absolute` would mean that the drawer would scroll with the page, but app-drawer is supposed to be fixed to the viewport. You can still achieve the result you described by doing something similar to the following example:

https://user-content-dot-custom-elements.appspot.com/PolymerElements/app-layout/v0.10.6/app-layout/demo/demo6.html (Code: https://github.com/PolymerElements/app-layout/blob/master/demo/demo6.html)

**Comment by govis** [comment]
Thanks for pointing it out - that works.

It might be useful if there was a way to listen to the app-header's height change (so that we could adjust the padding of the drawer as needed and possibly perform other layout scenarios when header condenses).

**Comment by keanulee** [comment]
That may not be very performant - if you have a condensing header, that may change height on every scroll event and changing padding requires layout. Maybe you can do something like add a scroll listener which reads the height of the header and `transform: translate()` the drawer contents, but even that might be expensive. Definitely beyond the scope of these elements tho.
