### ISSUE TITLE
<app-header-layout has-scrolling-region> not working in Safari when printing page

### ISSUE THREAD

**Issue by xxBedy** [PolymerElements/app-layout#408]
### Description
<app-header-layout has-scrolling-region>
all content is blank when printing page in Safari, works fine in Chrome.
### Expected outcome

Print content of <app-header-layout> tag.

### Actual outcome

"Test content" not printed

### Steps to reproduce

<app-drawer-layout fullbleed force-narrow>
  <app-drawer id="startDrawer">
    <app-toolbar>Menu
    </app-toolbar>
    <div class="drawer-list">
      <a routerLink="/a" routerLinkActive="iron-selected">A</a>
      <a routerLink="/b" routerLinkActive="iron-selected">B</a>
    </div>
  </app-drawer>

  
  <app-header-layout>

    <app-header condenses fixed effects="waterfall">
      <app-toolbar>
        <div class="titlepage" main-title>TITLE</div>
      </app-toolbar>
    </app-header>

    Test content.

  </app-header-layout>

</app-drawer-layout>
### Browsers Affected

- [OK] Chrome
- [? ] Firefox
- [X ] Safari 9
- [? ] Safari 8
- [?] Safari 7
- [?] Edge
- [?] IE 11
- [?] IE 10

**Comment by blasten** [comment]
Do you mind sharing the complete code? When using the demo, I see the following:
[app-header-layout.pdf](https://github.com/PolymerElements/app-layout/files/772009/app-header-layout.pdf)

**Comment by blasten** [comment]
Please reopen if this is still an issue.
