### ISSUE TITLE
app-grid class is not applied to distributed nodes

### ISSUE THREAD

**Issue by rslawik** [PolymerElements/app-layout#410]
### Description

app-grid class is not applied to distributed nodes

### Expected outcome

Distributed nodes can be styled by app-grid.

### Actual outcome

Distributed nodes are not styled.

### Live Demo

https://jsbin.com/fuxekesune/edit?html,output

**Comment by blasten** [comment]
Let me review this PR https://github.com/PolymerElements/app-layout/pull/396 again and merge it if looks good. Thanks!

**Comment by rslawik** [comment]
The merged solution uses a different approach. Clients are expected to add a container with class="app-grid":
```html
<my-element>
  <div slot="header">add to header</div>
  <div slot="grid-content">
    <div class="app-grid">
      <div>1</div>
      <div>2</div>
      <div>3</div>
    </div>
  </div>
</my-element>
```
I wanted to suggest:
```html
<my-element>
  <div slot="header">add to header</div>
  <div slot="gird-content">
      <div>1</div>
      <div class="wide-tile">2</div>
      <div>3</div>
  </div>
</my-element>
```
Is the former approach preferable? If so, why?
How can clients of `<my-element>` specify which child of the grid should be expandible? (E.g. "wide-tile" class in the latter approach.)

Currently the demo I prepared works in ShadyDOM, but not in ShadowDOM.

**Comment by blasten** [comment]
There are a few limitations in the custom property shim so I don't think we can support what you originally suggested. The current API tries to work around those limitations ;)

**Comment by rslawik** [comment]
Thank you for the explanation. I think it is worth documenting though.
For example a section to main `README.md` on how to use it (_app-grid_) for distributed children and which limitation we are trying to work around.

**Comment by rslawik** [comment]
A follow up question. Under Shadow DOM v1 it is no longer possible to [target a descendant](https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom#stylinglightdom) in the slotted subtree (only top-level elements). The accepted [solution](https://github.com/PolymerElements/app-layout/blob/master/app-grid/app-grid-style.html#L162):
```html
<x-foo>
  <ul class="app-grid">
    <li class="expand-me">item</li>
  </ul>
</x-foo>
```
will not work - there is no way of applying any styles to any of the descendants of `<ul>`.

**Comment by frankiefu** [comment]
Correct.  In Shadow DOM v1, `::slotted` can only take a `compound selector`.  So the support has been [dropped from app-grid in 2.0](https://github.com/PolymerElements/app-layout/pull/396#issuecomment-285529122).
