### ISSUE TITLE
Possible bug, queueing of afterNextRender callbacks by app-drawer.html 

### ISSUE THREAD

**Issue by santanubasu** [PolymerElements/app-layout#413]
### Description

Hi not sure if what I am seeing is a bug, a transient inconsistency, or I just don't understand something, but here goes.  

I am trying to use app-layout on the 2.0-preview branch, along with 2.0-preview of polymer itself of course.  In app-drawer.html, I see this code at line 265:

        Polymer.RenderStatus.afterNextRender(this, function() {
          this._styleTransitionDuration(this.transitionDuration);
          this._boundEscKeydownHandler = this._escKeydownHandler.bind(this);
          this._resetDrawerState();
          // contentContainer will transition on opened state changed, and scrim will
          // transition on persistent state changed when opened - these are the
          // transitions we are interested in.
          this.$.scrim.addEventListener('transitionend', this._transitionend.bind(this));
          this.$.contentContainer.addEventListener('transitionend', this._transitionend.bind(this));
          this.addEventListener('keydown', this._tabKeydownHandler.bind(this))
          // Only listen for horizontal track so you can vertically scroll inside the drawer.
          this.listen(this, 'track', '_track');
          this.setScrollDirection('y');
        });

And in render-status.html I see this code at line 47:

```
  Polymer.RenderStatus = {
    beforeNextRender: function(cb) {
      if (!scheduled) {
        schedule();
      }
      beforeRenderQueue.push(cb);
    },
    afterNextRender: function(cb) {
      if (!scheduled) {
        schedule();
      }
      afterRenderQueue.push(cb);
    }
  };

```
When I use these two together, I get an exception thrown at line 37 of render-status.html:

render-status.html:37 Uncaught TypeError: queue[i] is not a function
    at flushQueue (render-status.html:37)
    at render-status.html:29

What it looks like is the "this" that's passed in is being put on the queue as the callback.  Prior versions of render-status.html this worked I think because the argument signature to that call was different.  

Is this something that's just in flux at the moment and I should just wait a bit?

### Expected outcome

I would expect the callback to be queued and then called after render.

### Actual outcome

Exception is thrown on attempt to call callback

### Browsers Affected

Only tried in chrome so far, don't think this is browser dependent
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by santanubasu** [comment]
I just saw a PR that already addresses this, please close if that is accepted

**Comment by santanubasu** [comment]
https://github.com/PolymerElements/app-layout/pull/411

**Comment by frankiefu** [comment]
The actual fix should be in Polymer and this [PR](https://github.com/Polymer/polymer/pull/4323) has addressed it already.
