### ISSUE TITLE
Update API doc for 2.0-preview

### ISSUE THREAD

**Issue by arthurevans** [PolymerElements/app-layout#419]
Examples in API doc don't reflect the changes in the demo:

https://github.com/PolymerElements/app-layout/blob/2.0-preview/app-drawer-layout/demo/index.html#L43

https://github.com/PolymerElements/app-layout/blob/2.0-preview/app-drawer-layout/demo/index.html#L68

Didn't scrub for other instances, just noted this one that came up in the PSK update.

**Comment by arthurevans** [comment]
Ideally: API doc or component release notes should note this as a change _required specifically in 2.x_.

**Comment by frankiefu** [comment]
Fixed in https://github.com/PolymerElements/app-layout/pull/421
