### ISSUE TITLE
No way to control scroller with/in has-scrolling-region on app-header-layout

### ISSUE THREAD

**Issue by dman777** [PolymerElements/app-layout#422]
There is no way to control scroller with `has-scrolling-region`

```html
    <app-header-layout fullbleed has-scrolling-region>
      <!-- Drawer content -->
      <app-header fixed effects="waterfall">
        <app-toolbar>
          <paper-icon-button icon="menu" on-tap="_drawerToggle"></paper-icon-button>
          <div main-title class="app-name">Dolphin</div>
        </app-toolbar>
      </app-header>
         ...
        </app-drawer>

        <!-- Main content -->
        <iron-pages attr-for-selected="data-route"
          id="foo"
            scroll-target="document"
          selected="{{route}}"
          selected-attribute="activated">

          <user-login data-route="user-login"></user-login>
          <my-view1 
            data-route="my-view1"
            tabindex="-1"></my-view1>
        </iron-pages>

      </app-drawer-layout>
    </app-header-layout>
```

I have tried `scrollIntoView()` on `Polymer.dom(app.root).querySelector('app-header-layout')` with no success. In addition,  `window.scrollTo(0,0)` has no effect ether. [Nevermind app-scrollpos-control with scroll-target, does not work](
http://stackoverflow.com/questions/42574318/app-scrollpos-control-not-working-with-has-scrolling-region-and-scroll-target)

I was able to work around this with controlling the scroller on `iron-pages` using it's native `scrollIntoView()` method.

**Comment by blasten** [comment]
You can do the following:

```html
<app-header-layout fullbleed has-scrolling-region>
    <app-header fixed effects="waterfall" id="header">
```

```js
// Accessing the scroll target
document.getElementById('header').scrollTarget
```

```js
// Changing the scroll position
document.getElementById('header').scroll(x, y);
```

**Comment by dman777** [comment]
`document.getElementById('header').scroll(x, y);` worked....thanks!

**Comment by chwzr** [comment]
`// Accessing the scroll target
document.getElementById('header').scrollTarget`

This is returning 0 if using the default app-toolbox template 👎 

i need this to trigger the iron-scroll-threshold  correctly.
and how to access this scrollTarget in a iron-page (included in the app-header-layout)..?

**Comment by ziszo** [comment]
If you want to restore the scroll position of pages, you can use
**app-scrollpos-control**:

https://www.webcomponents.org/element/PolymerElements/app-layout/v1.0.1/elements/app-scrollpos-control
