### ISSUE TITLE
2.0-preview: app-drawer is not being showed up

### ISSUE THREAD

**Issue by mkutny** [PolymerElements/app-layout#428]
### Description
`app-drawer-layout` does not show up `app-drawer` in Polymer v2.
The code snippet is taken right from your app-drawer-layout Readme.

### Expected outcome
App-drawer expected to be shown (as in Polymer v1).

### Live Demo
http://plnkr.co/edit/zXmZeiNARQdda0CddCDs?p=preview

**Comment by keanulee** [comment]
Ah, thanks for letting us know @mkutny! I've updated the docs now.

**Comment by mkutny** [comment]
You still have `slot="header"` missing in "Drawer layout" section here: https://www.polymer-project.org/2.0/toolbox/app-layout
