### ISSUE TITLE
Sticky footer doesn't work in IE 11 when content is added

### ISSUE THREAD

**Issue by HJK181** [PolymerElements/app-layout#430]
### Description

The `app-header-layout` sticky footer demo doesn't work when content is added into the content div.
### Expected outcome

The sticky footer is at the bottom of the inserted content
### Actual outcome

The sticky footer stays at it's initial position at the view port bottom, not at the bottom of the content.
### Steps to reproduce

1. Put a `sample-content` element with size of 50 into the content div of the demo.
2. Open the page in IE 11
3. Scroll down and see the footer staying at its initial position.

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [X] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
The `app-layout/app-header-layout/demo/footer.html` demo seems to work fine for me in IE11 now.  Please let us if you still see the issue.

**Comment by abdonrd** [comment]
I have the same issue:

<img width="1389" alt="screen shot 2017-12-15 at 15 23 38" src="https://user-images.githubusercontent.com/1007051/34046072-f7e78db2-e1ab-11e7-97c4-f3fd4855aa80.png">

**Comment by keanulee** [comment]
If this is IE11 specific, it could be a bug with their vertical flexbox layout. In the footer demo, the `<div class="content">` element is `flex: 1` so it should take up the remainder of the vertical space.
