### ISSUE TITLE
app-drawer-layout causes the swipe-open in the app-drawer to change behaviour

### ISSUE THREAD

**Issue by hegsie** [PolymerElements/app-layout#431]
### Description
app-drawer-layout causes the swipe-open in the app-drawer to be fixed in place

### Expected outcome

Drawer to be closed on load

### Live Demo
https://jsfiddle.net/hegsie/aks0118p/

### Steps to reproduce

Removing the drawer layout element element changes the internal functionality of the app-drawer

### Browsers Affected

- [ X] Chrome
- [ X] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
@hegsie I'm not sure what you're trying to say - app-drawer-layout sets app-drawer to opened or closed depending on the width of the viewport (regardless of whether `swipe-open` is set on app-drawer). You can use app-drawer without layout, but you'll have to control the opened state yourself. Also in your demo, did you mean to put `<sample-content>` inside `<app-header-layout>`?

**Comment by hegsie** [comment]
Ah, you've jsut answered my confusion, I thought the layout component was required for the app-drawer
