### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by lozohcum** [PolymerElements/app-layout#432]
### Description
error:   Uncaught exception: Error: ENOENT: no such file or directory, open 'C:\Users\lozohcum\Documents\Repos\polymer-test\bower_compon                    ents\webcomponentsjs\webcomponents-lite.min.js'
error:   Error: ENOENT: no such file or directory, open 'C:\Users\lozohcum\Documents\Repos\polymer-test\bower_components\webcomponentsjs                    \webcomponents-lite.min.js'

**Comment by frankiefu** [comment]
duplicate of https://github.com/webcomponents/webcomponentsjs/issues/738
