### ISSUE TITLE
Dynamically loaded content may not be padded to fit under the header

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#436]
### Description

This is for 2.0-preview. When content in added to the <code>app-header-layout</code> at run-time via data binding or element lazy-loading it is may not be automatically padded to fit under the header.

### Expected outcome

![image](https://cloud.githubusercontent.com/assets/971651/24169280/7b11faec-0e53-11e7-8077-e1820ce1117b.png)

### Actual outcome

![image](https://cloud.githubusercontent.com/assets/971651/24170541/9d1945d8-0e57-11e7-956c-3c8967de3494.png)

### Live Demo
Try making the following change to <code>app-header-layout/demo/simple.html</code>
<pre><code>
&lt;!--&lt;link rel="import" href="../../demo/sample-content.html">-->
ready: function () {
    this.importHref(this.resolveUrl("../../demo/sample-content.html"));
}</code></pre>

I'm using app-layout version 2.0.0 (aka 2.0-preview)

Somehow this seems to be working in jsbin - I wonder if it's picking up the current master branch bits or gets resized via being in iframe or something:
http://jsbin.com/yijuduzuyo/edit?html,console,output

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Confirmed - I see this issue if I make a JSBin with 2.0-preview dependencies http://jsbin.com/mujepil/edit?html,console,output

**Comment by keanulee** [comment]
This is a result of lifecycle callback changes in Polymer 2.0. Specifically, in 2.0, `ready` is called _before_ attached, and `attached` is no longer deferred until after the first paint (see https://www.polymer-project.org/2.0/docs/about_20#lifecycle-changes). As a workaround, you should do the `importHref` inside a `requestAnimationFrame` in `attached`.

**Comment by govis** [comment]
Thank you for taking a look and explaining the lifecycle callback changes - your suggestion seems to work in this case, but there might still be some issues. 

I have the <code>app-header-layout</code> in a page that is one of a set, and is hidden (<code>display: none</code>) initially and becomes visible when loaded. When its' <code>display</code> attribute changes, <code>app-header-layout</code> doesn't seem to be setting the padding either.

I put together an example that should illustrate the issue: http://jsbin.com/mezedeqife/edit?html,output It doesn't even use importHref, and it's based on Polymer 2.0 native class syntax.

**Comment by frankiefu** [comment]
You need to call [resetLayout()](https://github.com/PolymerElements/app-layout/blob/2.0-preview/app-layout-behavior/app-layout-behavior.html#L44) or implement [iron-resizable behavior ](https://github.com/PolymerElements/iron-resizable-behavior) (which is what iron-pages does). That way `app-header-layout` knows there are changes to the content and should update the layout.

**Comment by govis** [comment]
That makes a lot of sense, Thank you for your help.
