### ISSUE TITLE
 app-header-layout scrollTop is not honored

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#439]
### Description
<code>scrollTarget.scrollTop</code> set by <code>appHeader.scroll(0, SCROLL_POSITION);</code> as per #404 seems to be ignored.

app-layout version 2.0.0 (2.0-preview)

### Expected outcome
Header layout to  scroll to a condensed state

### Actual outcome
Header layout does not scroll

### Live Demo
http://jsbin.com/bimefoquza/edit?html,console,output

### Steps to reproduce
Run the sample

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
I took a quick look at your jsbin and the issue is `scroll` is called too early.  If you call it later e.g. in a `setTimeout` or call `Polymer.flush` before calling `scroll` ([demo](http://jsbin.com/civisobuna/edit?html,console,output)) then it should work.

**Comment by govis** [comment]
Thanks, I figured it might be a timing issue. I've been calling it from <code>async</code> and it used to give enough of a delay, but not anymore. If there's no consistent timing as to how long to wait before calling <code>scroll</code> then <code>Polymer.flush</code> might be the only option unless there's some way to hook onto an event when the <code>layout</code> is ready to scroll?
