### ISSUE TITLE
switch to font-roboto-local

### ISSUE THREAD

**Issue by cordovapolymer** [PolymerElements/app-layout#441]
Please switch to font-roboto-local because polymer-build doesn't bundle it https://github.com/Polymer/polymer-build/issues/155

**Comment by frankiefu** [comment]
app-layout itself doesn't import `font-roboto/roboto.html`.  In your apps using `app-layout` you should be able to pick either `font-roboto/roboto.html` or `font-roboto-local/roboto.html` to import.

**Comment by cordovapolymer** [comment]
@frankiefu , it does import it in [index.html](https://github.com/PolymerElements/app-layout/blob/master/index.html) and also in demos
https://github.com/PolymerElements/app-layout/search?p=1&q=font-roboto&type=&utf8=%E2%9C%93

**Comment by web-padawan** [comment]
@cordovapolymer you can override `font-roboto` to use local [like this](https://github.com/web-padawan/polymer-sandbox/blob/master/bower.json#L7) without rewriting any HTML imports.

And another thing, as you can see [here](https://github.com/PolymerElements/app-layout/blob/master/bower.json#L23) `app-layout` requires `font-roboto` as a dev dependency and thoseare not being installed when running `bower install`.
