### ISSUE TITLE
app-header-layout not showing safari and Facebook browser.

### ISSUE THREAD

**Issue by szk360** [PolymerElements/app-layout#456]
### Description

app-header-layout not showing. I found error on safari concole log.

[Error] TypeError: document.registerElement is not a function. (In 'document.registerElement('dom-module', DomModule)', 'document.registerElement' is undefined)
	（anonymous関数） (data:text/javascript;charset=utf-8,(fu…%0A:441)
	グローバルコード (data:text/javascript;charset=utf-8,(fu…%0A:456)
[Error] TypeError: Polymer.Base._getExtendedPrototype is not a function. (In 'Polymer.Base._getExtendedPrototype(prototype.extends)', 'Polymer.Base._getExtendedPrototype' is undefined)
	desugar (data:text/javascript;charset=utf-8,(fu…%0A:60)
	Polymer (data:text/javascript;charset=utf-8,(fu…%0A:47)
	（anonymous関数） (data:text/javascript;charset=utf-8,(fu…%0A:4169)
	グローバルコード (data:text/javascript;charset=utf-8,(fu…%0A:4271)
[Error] TypeError: this._desugarBehaviors is not a function. (In 'this._desugarBehaviors()', 'this._desugarBehaviors' is undefined)
	registerCallback (data:text/javascript;charset=utf-8,(fu…%0A:182)
	desugar (data:text/javascript;charset=utf-8,(fu…%0A:63)
	Polymer (data:text/javascript;charset=utf-8,(fu…%0A:47)
	（anonymous関数） (data:text/javascript;charset=utf-8,%0A…%0A:10)
	グローバルコード (data:text/javascript;charset=utf-8,%0A…%0A:279)
[Error] TypeError: this._desugarBehaviors is not a function. (In 'this._desugarBehaviors()', 'this
### Steps to reproduce

please try sample page in safari.
https://user-content-dot-custom-elements.appspot.com/PolymerElements/app-layout/v1.0.0/app-layout/app-header-layout/demo/simple.html

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
Thanks for the report.  There was a mistake in bower.json which points to an incorrect version of webcomponentsjs.  We just tagged a new version which should have fixed the issue: https://github.com/PolymerElements/app-layout/releases/tag/v1.0.1

**Comment by szk360** [comment]
Hello, Frankie

Thanks for quick responce.

Regards,
Takahiro

2017-04-15 10:18 GMT+09:00 Frankie Fu <notifications@github.com>:
