### ISSUE TITLE
Drawer toggle element responds to click event, not tap

### ISSUE THREAD

**Issue by tmlbl** [PolymerElements/app-layout#465]
When using the app-drawer-layout in a progressive application, the handler that toggles the drawer listens to the `click` event, not the `tap` event: [code here](https://github.com/PolymerElements/app-layout/blob/222ae2cc99cc8111ddc188b05791b80edc55cb0d/app-drawer-layout/app-drawer-layout.html#L211)

If the listener is changed to `tap`, the original behavior is preserved, and the drawer opens more quickly on mobile devices since the `tap` event bypasses the 300ms click delay. Since toggling the drawer is a common operation on mobile, it makes sense for this behavior to tie in to the `tap` event.

**Comment by keanulee** [comment]
@tmlbl The `tap` event was created at a time when `click` events were delayed by mobile browsers, but this is not the case anymore (https://webkit.org/blog/5610/more-responsive-tapping-on-ios/). Moving forward, we recommend using the native `click` event instead.
