### ISSUE TITLE
2.0-preview: Drawer close animation fails on iOS

### ISSUE THREAD

**Issue by tmlbl** [PolymerElements/app-layout#468]
When running on iOS with the 2.0-preview branch and Polymer starter kit, the drawer animates properly when opening. However, when closing, it pauses for the `transitionDuration` and then disappears instantly.

I have dug into the issue in web inspector to no avail. When manually toggling the `opened` attribute via the inspector, the animation is performed correctly, and the `opened` property is being modified by Polymer in the same fashion as elsewhere. This is likely an issue with Mobile Safari and not Polymer, but if a workaround can be devised, user experience would benefit.

Safari version is 10.0 (iOS 10.3.1)

**Comment by keanulee** [comment]
Related: https://bugs.webkit.org/show_bug.cgi?id=170762

**Comment by frankiefu** [comment]
We have a workaround for the Safari issue: https://github.com/PolymerElements/app-layout/pull/471/files#diff-f38724fad504d9969ea7ff9552ed60d8R172
