### ISSUE TITLE
[2.0-preview] app-drawer-layout doesn't render contentContainer in Firefox

### ISSUE THREAD

**Issue by runia1** [PolymerElements/app-layout#472]
### Description
In firefox app-drawer-layout doesn't render contentContainer.  For example:
```html
<app-drawer-layout fullbleed>
  <app-drawer slot="drawer">
     drawer content
  </app-drawer>
  <div>
    main content
  </div>
</app-drawer-layout>
```
Will render the app-drawer, but the div will not get rendered.  It's as if it just isn't there at all.
![max___emily](https://cloud.githubusercontent.com/assets/6709518/26009847/d3919f38-3707-11e7-92a8-d1d279c9f9f1.png)

### Live Demo
https://honeymoon.mrunia.com

### Steps to reproduce
```
git clone https://github.com/runia1/honeymoon_app
npm install
npm run build
node build/server.js
```
... look at localhost:8080 in firefox, chrome, safari.
Firefox just doesn't show anything slotted into contentContainer, and in fact doesn't even show `<div id="contentContainer">` at all.

### Browsers Affected
- [ ] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by runia1** [comment]
Was able to fix by changing:
```html
    <slot id="drawerSlot" name="drawer"></slot>

    <div id="contentContainer">
      <slot></slot>
    </div>

    <iron-media-query
        query="[[_computeMediaQuery(forceNarrow, responsiveWidth)]]"
        on-query-matches-changed="_onQueryMatchesChanged"></iron-media-query>
```
to:
```html
    <slot id="drawerSlot" name="drawer"></slot>

    <slot id="contentContainer"></slot>

    <iron-media-query
        query="[[_computeMediaQuery(forceNarrow, responsiveWidth)]]"
        on-query-matches-changed="_onQueryMatchesChanged"></iron-media-query>
```

and this:
```js
_updateLayoutStates: function() {
        var drawer = this.drawer;
        var contentContainer = this.$.contentContainer;
```
to: 
```js
_updateLayoutStates: function() {
        var drawer = this.drawer;
        var contentContainer = this.$.contentContainer.assignedNodes()[0];
```

I suspect that this is not the best way to do it, but I didn't have the time really look into it.

**Comment by frankiefu** [comment]
Thanks for the report. We also saw the issue and we are working on a fix in Polymer 2.x.

**Comment by frankiefu** [comment]
This should be fixed in https://github.com/Polymer/polymer/releases/tag/v2.0.0-rc.9

**Comment by runia1** [comment]
@frankiefu Awesome!  It's been my experience that the polymer team has been slow to respond to issues I've submitted, nice to see someone respond right away!
