### ISSUE TITLE
ECONFLICT Unable to find suitable version for app-layout

### ISSUE THREAD

**Issue by OlgaShirokova** [PolymerElements/app-layout#474]
Hi,

When I run `bower install PolymerElements/app-layout --save` like mentioned in your docs, I get this error message:

```sh
ECONFLICT Unable to find suitable version for app-layout
```

Can you please check it out? Thx!

@blasten @keanulee @frankiefu @tedium-bot

**Comment by OlgaShirokova** [comment]
Oh, I see the conflict was due to another version of the library being already present in my `bower.json`. Thx!

**Comment by keanulee** [comment]
Running `bower install` will install the latest tagged version of app-layout which is currently `2.0.0`. This does not match the range `^0.10.0`, so you'll need to update that.
