### ISSUE TITLE
Not found files

### ISSUE THREAD

**Issue by chinh2525** [PolymerElements/app-layout#478]
I can't find some files

  <script src="../../webcomponentsjs/webcomponents-lite.js"></script>

  <link rel="import" href="../../font-roboto/roboto.html">
  <link rel="import" href="../../iron-icons/iron-icons.html">
  <link rel="import" href="../../paper-icon-button/paper-icon-button.html">

**Comment by frankiefu** [comment]
I assumed you just checked out the repo and tried to run the demo directly? You will need to install dependencies using `bower install` and `polymer serve` to help serving the files. Take a look at the doc here: https://www.polymer-project.org/2.0/start/first-element/intro
The doc uses `polymer-2-first-element` as an example but the same workflow ([Install dependencies and run the demo](https://www.polymer-project.org/2.0/start/first-element/intro#install-dependencies-and-run-the-demo)] works for other elements too.
