### ISSUE TITLE
app-header threshold/thresholdTriggered vs condensing height

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#479]
<code>app-header's threshold/thresholdTriggered</code> properties are useful yet somewhat limiting. For example one can use them to determine if the header is in half or fully condensed state but not both.

Could we expose the header's <code>condensing height</code> instead of (or along with) the <code>thresholdTriggered</code> for additional flexibility? For a condensing header it would be height - <code>scrollTop</code> or height of the sticky element (whichever is larger) and could be done by adding <code>Polymer.AppScrollEffectsBehavior._scrollHandler</code> override in <code>app-header</code>.

This way we can let the client decide which threshold breakpoint is triggered and it would support additional scenarios such as when content needs to be padded dynamically similarly to how app-header-layout does it e.q. having <code>app-drawer-layout</code> inside an <code>app-header-layout</code> with a condensing header. Thanks.

**Comment by govis** [comment]
Looks like it can also be done manually by attaching a scroll listener as in notes demo:

https://github.com/PolymerElements/app-layout/blob/master/app-header/demo/notes.html#L149-L168

Not sure if it's common enough, so I'll leave it up to you, please close as you see fit.

**Comment by frankiefu** [comment]
Yeah, listening for scroll events are the suggested way to achieve what you want. Thanks for the feedback.
