### ISSUE TITLE
App drawer closed.

### ISSUE THREAD

**Issue by fmatuszewski** [PolymerElements/app-layout#480]
When layout is wide the drawer is always opened how to make it closed by default in wide .
I use polymer toolbox.

**Comment by frankiefu** [comment]
Sounds like you just need app-drawer without app-drawer-layout. See this example: https://www.webcomponents.org/element/PolymerElements/app-layout/demo/app-drawer/demo/left-drawer.html

**Comment by steve-a-jones** [comment]
You might also consider using the `force-narrow` boolean property on `app-drawer-layout` to force the "narrow layout" view.

ie..
`<app-drawer-layout force-narrow>`

https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/app-drawer-layout.html#L196
