### ISSUE TITLE
app-header, when used inside app-header-layout needs slot="header" to work

### ISSUE THREAD

**Issue by akc42** [PolymerElements/app-layout#484]
I have just transitioned to Polymer 2, and my app-header-layout failed, with the main content going over the header.   

After some discussion on the Polymer Slack Channel and closely looking at the example on webcomponents.org I can see that you need to add slot="header" to the app-header element.  

This needs some explicit documentation so people know what to do, rather than infer it from an example.

**Comment by frankiefu** [comment]
@akc42 Sorry about that. The [Readme](https://github.com/PolymerElements/app-layout#changes-in-app-layout-20) has a section about "Changes in App Layout 2.0" but it's also true it doesn't explicitly say one needs to put `slot="header"` in `app-header` when it's inside `app-header-layout`, and instead it just says you need to do something similar to `app-header-layout`.
