### ISSUE TITLE
app-drawer-layout does not resize contentContainer on drawer close

### ISSUE THREAD

**Issue by cvicentiu** [PolymerElements/app-layout#485]
### Description

The app-drawer-layout does not correctly resize content when the drawer gets closed.
This example https://user-content-dot-custom-elements.appspot.com/PolymerElements/app-layout/v0.10.6/app-layout/demo/demo6.html no longer works following commit:

https://github.com/PolymerElements/app-layout/commit/91b5151aa739ef4d206477f4f3f8e4688bfd7f98

The problem is that the \#contentContainer does not get resized after closing the drawer in wide-view mode. (see my next comment on issue)

### Expected outcome
contentContainer expands to fill available space.

### Actual outcome
Content container remains fixed in position.

### Live Demo

https://jsbin.com/noqiqanike/1/edit?html,output
### Steps to reproduce
Click the button in the example. Drawer retracts, content stays put. :(
### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cvicentiu** [comment]
After further looking at the demo, I realize the demo makes use of forceNarrow to widen the content. I don't think that it is how the toggle behaviour should work. Either way, after the commit I linked, there is no more animation for contentContainer, when it does resize. It just jumps to the wider width.

**Comment by frankiefu** [comment]
@cvicentiu The demo seems to work fine in the `v2.0.0` of `app-layout`: 
[live demo](https://user-content-dot-custom-elements.appspot.com/PolymerElements/app-layout/v2.0.0/app-layout/demo/demo6.html)
[source](https://github.com/PolymerElements/app-layout/blob/master/demo/demo6.html)

As you have already indicated, you need to use `forceNarrow` to toggle the drawer and there is also a CSS to make the drawer to transition: https://github.com/PolymerElements/app-layout/blob/master/demo/demo6.html#L51

The setup has always been like this and I don't see the commit you linked is causing an issue.

**Comment by cvicentiu** [comment]
@frankiefu Yes, you are right. Thanks for the clarification. At first I thought that the code there gets called multiple times to set the width "per frame". I didn't notice the CSS transition part. On the other hand, I argue that on a not-narrow display, the button toggle should allow the contentContainer to resize according to the leftover space, without having to call forceNarrow. My expectation was that 
```
      if (drawerLayout.forceNarrow || !drawerLayout.narrow) {
        drawerLayout.forceNarrow = !drawerLayout.forceNarrow;
      } else {
        drawerLayout.drawer.toggle();
      }
```
should be like
```
drawerLayout.drawer.toggle();
```
for all screen widths. It was a bit of a challenge for me to figure out how all the parts interact.
