### ISSUE TITLE
drawer-layout and header-layout are not printer-friendly

### ISSUE THREAD

**Issue by pdesjardins90** [PolymerElements/app-layout#487]
### Description
```<app-drawer-layout>``` and ```<app-header-layout>``` with fullbleed and has-scrolling-region attributes set are not printer-friendly when content is longer than the viewport (scrollable).

### Context
With user code:
```html
<app-drawer-layout fullbleed>
  <app-header-layout fullbleed has-scrolling-region>
    <content></content>
  </app-header-layout>
</app-drawer-layout>
```
Where ```<content>``` is longer than the viewport,
When printing

### Expected outcome

=> The print preview should have multiple pages and show all the content

### Actual outcome

=> The print preview only have one page and shows only the content corresponding to the current view (where the user has scrolled)

### Live Demo
  This [JS Bin](http://jsbin.com/hihatef/1/edit?html,output), but you won't be able to reproduce the problem in there directly, you'll have to copy paste the html in a file and open it with your browser.

### Steps to reproduce

1. Use the layout described in the 'Context' section back up
2. Replace ```<content>``` with some content that goes over multiple pages
3. Scroll down a bit
4. Print that

**Comment by pdesjardins90** [comment]
I've tried binding ```fullbleed``` and ```has-scrolling-region``` to an iron-media-query for print, but it just broke the css (fullbleed is not bindable because it lacks a property with a reflectToAttribute config). 

Even when hotpatching this, the iron-media-query matches multiple times when pressing print (shared state between the print preview and the browser viewport I guess?) and it results in the query-matches variable to be false, so the print preview don't update as expected anyway.

**Comment by pdesjardins90** [comment]
Is anybody out there?

**Comment by frankiefu** [comment]
@pdesjardins90 Sorry about the late response. This got lost somehow. Seem like the issue is caused by `has-scrolling-region` uses the scroller internally and `overflow: auto` is not good for print. Instead we should switch to `overflow: visible` when in `print` mode. Maybe something like the following in `app-header-layout.html`:
```
@media print {
  :host([has-scrolling-region]) #wrapper #contentContainer {
    overflow-y: visible;
  }
}
```

**Comment by pdesjardins90** [comment]
Thanks for the reply! Seems a good idea for the scrolling problem at least. I'll have to take a closer look at this again, seems my PR included media queries around absolute positioning stuff too. I'll get back at you tomorrow with that

**Comment by pdesjardins90** [comment]
Just tried your code block instead of what's in the PR, it works fine too! Since it's less invasive than what I initially proposed, I'm gonna update my PR with that.
