### ISSUE TITLE
dom-repeat is taking space in app-grid

### ISSUE THREAD

**Issue by wsmlby** [PolymerElements/app-layout#491]
### Description

dom-repeat is taking space in app-grid
### Expected outcome
<dom-repeat> in the tree inside app-grid take 0 space

### Actual outcome
<dom-repeat> in the tree inside app-grid take extra space like a real item

### Live Demo

![image](https://user-images.githubusercontent.com/1570401/27024024-e7ec00f8-4f09-11e7-85e5-c0268433576d.png)

### Steps to reproduce

1. Go to demo [Link](https://www.webcomponents.org/element/PolymerElements/app-layout/demo/app-grid/demo/index.html) use chrome
2. open dev-tools open and click toggle device toolbar.

### Browsers Affected

- [x ] Chrome

**Comment by jsilvermist** [comment]
As a temporary workaround, you can add the `hidden` attribute to `dom-repeat` to set `display: none`.

**Comment by keanulee** [comment]
app-grid will layout all its children, so styling `dom-repeat` as `display: none` is a good suggestion.
