### ISSUE TITLE
app-drawer ignores display: none on app-drawer-layout

### ISSUE THREAD

**Issue by mbleigh** [PolymerElements/app-layout#493]
### Description

I add a `display: none;` to an `<app-drawer-layout>`.

### Expected outcome

The `<app-drawer>` is also `display: none;` when greater than responsive width.

### Actual outcome

The `<app-drawer>` is still visible and must be hidden separately.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
@mbleigh I can't seem to reproduce it in the jsbin: http://jsbin.com/koxatunoyo/2/edit?html,output
