### ISSUE TITLE
npm install fails, dependency @polymer/iron-flex-layout@gloo not found

### ISSUE THREAD

**Issue by Noah-Huppert** [PolymerElements/app-layout#496]
### Description
When trying to install the app-layout package with NPM it fails with the following error:

```
$ npm install @polymer/app-layout --save 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @polymer/iron-flex-layout@gloo
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of '@polymer/app-layout'
npm ERR! notarget 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/noah/.npm/_logs/2017-07-13T03_29_31_549Z-debug.log
```

[Link to complete debug.log specified in above error message](https://gist.github.com/Noah-Huppert/824d81914ddb3b188196675a199305a5)

It looks like the app-layout package on NPM is specifying the iron-flex-layout package with the version tag `gloo`. This seems very odd and not like any expected behavior. 

I looked in the app-layout and iron-flex-layout repositories and I couldn't find any dependencies with the tag `gloo`.

### Expected outcome
The package installs successfully with NPM.

### Actual outcome
The package install fails with an very odd dependency error. Which insists that the package iron-flex-layout is required as a dependency with the version tag `gloo`.

### Live Demo
Unfortunately I can not provide a live demo as this is a NPM install issue. Hopefully with the provided system info and the steps below the issue can be reproduced.

System info:
```
$ uname -a
Linux Ikebukuro 4.11.6-1-ARCH #1 SMP PREEMPT Sat Jun 17 08:19:42 CEST 2017 x86_64 GNU/Linux

$ cat /etc/*-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

$ npm --version
5.2.0
```

### Steps to reproduce
1. Create an empty directory and cd into it
2. Run `npm init` and fill out fields appropriately
3. Install Polymer first, `npm install @polymer/polymer --save`
5. Next attempt to install app-layout, `npm install @polymer/app-layout --save`
    - I have determined that this issue occurs with and without the save flag
5. Install fails with a dependency error

### Browsers Affected
None, developer side install issue

**Comment by Balavaradh** [comment]
Any update on this issue

**Comment by Noah-Huppert** [comment]
I never solved this. I kinda just stopped using polymer. The combination of
this issue and all the cross compiling tomfoolery was too much for me.

**Comment by keanulee** [comment]
@Balavaradh You need to use `npm install @polymer/app-layout@next` - see https://www.polymer-project.org/blog/2017-08-23-hands-on-30-preview.html
