### ISSUE TITLE
--app-drawer-content-container mixin is not being applied

### ISSUE THREAD

**Issue by Shakarhaba** [PolymerElements/app-layout#497]
### Description
The `app-drawer` --app-drawer-content-container mixin is not being applied.

### Expected outcome
The drawer should have a red background as the background-color property is being replaced by the mixin.

### Actual outcome
The drawer continues having the default background set in app-drawer.html (that's it: #FFF).
The mixin is not being applied.

### Live Demo
https://jsbin.com/xevajizela/edit?html,css,output

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by frankiefu** [comment]
Use `<custom-style>` for defining styles in the main document to take advantage of custom properties shims and mixin.  See this updated jsbin: http://jsbin.com/niluyefeqo/edit?html,output
