### ISSUE TITLE
drawer-toggle in custom element

### ISSUE THREAD

**Issue by krisu7** [PolymerElements/app-layout#502]
### Description
I extend app-toolbar element and want to use drawer-toggle
`<paper-icon-button icon="my-icons:menu" slot="drawer-toggle" drawer-toggle></paper-icon-button>`

### Expected outcome
Menu icon shows when layout is narrow, when clicked opens drawer.

### Actual outcome
Menu icon is not showing.

### Browsers Affected
- [X ] Chrome

I only tested on chrome

**Comment by keanulee** [comment]
There is not `<slot>` named `drawer-toggle` in app-drawer-layout. Please see this sample code https://github.com/PolymerElements/app-layout/blob/master/app-drawer-layout/app-drawer-layout.html#L85

**Comment by frankiefu** [comment]
Closing this as it seems like an incorrect usage on `app-drawer`. Please reopen if this is still an issue.
