### ISSUE TITLE
What's the license of images used in the Shrine app?

### ISSUE THREAD

**Issue by antonmoiseev** [PolymerElements/app-layout#509]
I'm creating an Angular application that has UI similar to the Shrine app. The question is - can the images from the Shrine app be used in other non-commercial open source apps created for learning purposes? The screenshots of the Angular app will be used in a paid book.

**Comment by keanulee** [comment]
No, the images are not part of this repo and are not covered by the same open-source license.

**Comment by antonmoiseev** [comment]
OK, thanks.
