### ISSUE TITLE
app-layout-behavior broken for Safari 10.1 & TP in polymer 3.0-preview

### ISSUE THREAD

**Issue by Camelion** [PolymerElements/app-layout#511]
### Description

In Polymer 3.0-preview `app-layout-behavior` is broken for Safari 10.1 and TP.

Import of this behavior fails with: `SyntaxError: Cannot use keyword as imported binding name.` when any element with app-layout-behavior is imported.
After some research i found, that it fails on:
```javascript
import * as async from '../../polymer/lib/utils/async.js';
```
Think that `async` can be renamed to `_async` or some other in this case.

### Expected outcome

Elements, that uses `app-layout-behavior` can be imported to other elements in Safari Browser in Polymer 3.0-preview
### Actual outcome

Elements, that uses `app-layout-behavior` fails on import in Safari Browser on Polymer 3.0-preview

### Steps to reproduce

1. import element with AppLayoutBehavior, e.g. AppHeaderLayout in your script
2. Open the page in a web browser.
3. Page will not be loaded, go to console and see `SyntaxError: Cannot use keyword as imported binding name.`

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [x] Safari 10.1
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by bicknellr** [comment]
Polymer/polymer-modulizer#197

**Comment by daflair** [comment]
Yeah, changing it to _async or $async makes it possible to import the following:
app-layout/app-drawer-layout/app-drawer-layout.js
app-layout/app-header/app-header.js

**Comment by venicia** [comment]
Any updates on this issue?

**Comment by keanulee** [comment]
This issue has been fixed in WebKit and is currently in Safari TP
