### ISSUE TITLE
App header does not react on scroll

### ISSUE THREAD

**Issue by willydouhard** [PolymerElements/app-layout#512]
### Description
The app header does not react on scroll (reveal effect)

### Expected outcome
The app header hides on scroll down and reveals itself on scroll up

### Actual outcome
Nothing happens, the app header stays on top

### Live Demo
https://ptitcoinsavonnerie.fr

### Steps to reproduce

- chrome Desktop Windows & Mac 60.0.3112.113 (60+ I think)
- "polymer": "Polymer/polymer#^1.9.1"
- "app-layout": "PolymerElements/app-layout#^0.10.7"

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Provided demo seems to be functional. Also, the version of app-layout specified seems to be old (currently 2.x).
