### ISSUE TITLE
App-Drawer not completely covering other elements

### ISSUE THREAD

**Issue by tdmiller1** [PolymerElements/app-layout#515]
### Description
App-drawer displays when toggled but doesn't completely cover other elements in the main body.

### Expected outcome

App-drawer takes complete precedence and shadows out every other element and overlays.

### Actual outcome
```
<na-toolbar
  		signed-in="[[signedIn]]"
    	        on-sign-out="signOut">
    </na-toolbar>

    <div disabled="[[online]]">
    	<resume-app></resume-app>
    </div>
```

app-drawer is currently inside <na-toolbar></na-toolbar>

```
<app-drawer-layout>
      <app-drawer slot="drawer">
        <div>Example 1</div>
      </app-drawer>
      <app-header-layout>
        <app-header slot="header">
          <app-toolbar>
            <paper-icon-button icon="menu" drawer-toggle></paper-icon-button>
          </app-toolbar>
        </app-header>
      </app-header-layout>
    </app-drawer-layout>
```

App-drawer displays behind other content from <resume-app></resume-app>

**Comment by keanulee** [comment]
`app-drawer` needs to be outside of any [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) in your app (which sounds like `na-toolbar` is creating). Consider moving `app-drawer` to the top level.

Related: https://github.com/PolymerElements/app-layout/issues/295
