### ISSUE TITLE
Linking to an anchor hides it beneath the header in app-header-layout

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/app-layout#519]
### Description
Linking to an anchor inside an `app-header-layout` scrolls too far down. It is off by the margin top and thus has the header behind the `app-header`

### Expected outcome

The page should link to the anchor as first item just beneath the `app-header`

### Actual outcome

The page scrolls the height of the header too far down and thus the anchor is beneath the `app-header`.

### Live Demo
https://chromedevtools.github.io/devtools-protocol/tot/Network/#type-LoaderId

```html
<app-header-layout mode="waterfall">
    <app-header slot="header" fixed>
      <app-toolbar id="mainToolbar">
        <div main-title class="top title">
          Chrome DevTools Protocol Viewer
        </div>
      </app-toolbar>
    </app-header>

    <div class="content">
      Content here that is long enough and has an anchor (e.g. `name` or `id`)
    </div>
  </app-header-layout>
```

### Steps to reproduce
1. Use a fixed `app-header-layout`
2. Have an anchor in the content
3. Open the webpage that has to scroll into the anchor.
### Browsers Affected

- [X] Chrome
- [ ] Firefox (does not scroll at all)
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
app-header/layout doesn't do anything special with hash-link scrolling - this is just what happens when you have a fixed-position element overlaying the document scroller.

Example: http://output.jsbin.com/goyazan#section3

**Comment by TimvdLippe** [comment]
@keanulee Thanks for the explanation. This was unexpected behavior for me, but I guess it makes sense. I have dropped our usage of `<app-header-layout>` (but remained using `<app-drawer-layout>`) and it is working as we expect now 😄
