### ISSUE TITLE
app-layout.html was not replaced with app-layout.js

### ISSUE THREAD

**Issue by itspiratefairy** [PolymerElements/app-layout#526]
### Description
In the 3.0 preview
as polymer 3.0 shifted to using es6 modules instead of html imports , this particular  app-layout.html still needs to be imported using html imports in the index.html file

### Steps to reproduce

the 'app-layout.html' file can be replaced by 'app-layout.js' file as show below, which can then be imported directly from other modules

#### file:app-layout.html
`
<script type="module" src="./helpers/helpers.js"></script><br />
<script type="module" src="./app-drawer/app-drawer.js"></script><br />
<script type="module" src="./app-drawer-layout/app-drawer-layout.js"></script><br />
<script type="module" src="./app-grid/app-grid-style.js"></script><br />
<script type="module" src="./app-header/app-header.js"></script><br />
<script type="module" src="./app-header-layout/app-header-layout.js"></script><br />
<script type="module" src="./app-toolbar/app-toolbar.js"></script><br />
<script type="module" src="./app-box/app-box.js"></script>
`

#### file: app-layout.js

import "./helpers/helpers.js"
import "./app-drawer/app-drawer.js"
import "./app-drawer-layout/app-drawer-layout.js"
import "./app-grid/app-grid-style.js"
import "./app-header/app-header.js"
import "./app-header-layout/app-header-layout.js"
import "./app-toolbar/app-toolbar.js"
import "./app-box/app-box.js"

**Comment by keanulee** [comment]
We'll probably need to fix this with the modulizer tool (referenced above), not per element repo.

**Comment by keanulee** [comment]
Fixed by latest output from modulizer https://github.com/PolymerElements/app-layout/blob/__auto_generated_3.0_preview/app-layout.js
