### ISSUE TITLE
Polymer.html is not a function

### ISSUE THREAD

**Issue by tjb1982** [PolymerElements/app-layout#531]
https://github.com/PolymerElements/app-layout/blob/f40cde23eac278201d04891c5bffa6f6659427b8/app-drawer/app-drawer.js#L67

Polymer is being imported as `Polymer$0` but this code is trying to use `Polymer` which hasn't been imported.

**Comment by keanulee** [comment]
Should be fixed by the latest output from modulizer https://github.com/PolymerElements/app-layout/blob/__auto_generated_3.0_preview/app-drawer/app-drawer.js
