### ISSUE TITLE
<app-header-layout has-scrolling-region> has additional unwanted "scroll region" on mobile chrome

### ISSUE THREAD

**Issue by andrewspy** [PolymerElements/app-layout#533]
### Description
Using Polymer Starter Kit as a sample, when using `has-scrolling-region` attribute on mobile Chrome with a page that is larger than the mobile screen, an additional unwanted "scroll region" appears when scroll all the way to the end of the screen (where the Chrome Address Bar fades away), and scroll back up.

### Expected outcome

No additional unwanted "scroll region".

### Actual outcome

![screenshot_20180210-131346](https://user-images.githubusercontent.com/3106425/36064290-c2bc7d7e-0ec3-11e8-8a8f-29490af9fa3c.png)

Additional unwanted "scroll region" visible at the bottom.

### Live Demo

https://x-psk3-init.firebaseapp.com/

### Steps to reproduce

1. Install polymer-starter-kit with `polymer init`.
2. Create additional cards (i.e. 3 cards) in `<my-view1>` so that it span more than mobile view.
3. Scroll to the bottom of the page until the Chrome Address Bar fades away, then scroll back up the page to reveal the unwanted "scroll region".

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
`has-scrolling-region` sets the height of `<app-header-layout>` to 100% of `<app-drawer-layout fullbleed>`, which has `postion: absolute; top: 0; bottom: 0`. The absolute-positioned element doesn't seem to resize when the URL bar scrolls away, so that's why you see the empty region. Consider setting `body { overflow: hidden }` to prevent the URL bar from scrolling away, or remove `has-scrolling-region` to use the document scroller.

**Comment by andrewspy** [comment]
@keanulee I have tried setting `body {overflow: hidden;}`, but it does not prevent the URL bar from scrolling away.

Also removing `has-scrolling-region` will make the UX less ideal as whenever scrolling back up, the URL bar will scroll back in first, rather than the `<app-header>`.

**Comment by keanulee** [comment]
Ah forgot to take a look at the existing CSS on `body` - I think you can prevent the URL bar from scrolling away by just removing `min-height: 100vh` rule (https://github.com/Polymer/polymer-starter-kit/blob/master/index.html#L99).

**Comment by andrewspy** [comment]
@keanulee `body {overflow: hidden;}` does prevent the URL bar from scrolling away after removing `min-height: 100vh`. But it still make the UX less ideal as the URL bar takes away 15% of the screen real estate permanently.

Shall I mark this close due to technical limitation of the browser? Or is there another way to workaround the limitation for a better UX?

**Comment by keanulee** [comment]
There's no way to manually control the URL bar, so unfortunately those are the only options. If a user adds your app to the homescreen though it becomes fullscreen so it won't be an issue then.

**Comment by FluorescentHallucinogen** [comment]
@keanulee @andrewspy Could you please take a look at https://github.com/googlearchive/note-app-elements/issues/18. Is this the same problem?

**Comment by andrewspy** [comment]
@FluorescentHallucinogen Yes, I think it's the same issue.

**Comment by stucker71** [comment]
I'm having the same issue. I'm sure many would be grateful if another solution was proposed other than preventing the URL bar from scrolling away and taking away a least 15% of the screen.

**Comment by stucker71** [comment]
I was having some scroll issues with mobile safari. After reading @keanulee comments above I tried:

```
    app-drawer-layout {
        position: fixed;
        top: 0;
        right: 0;
        bottom: 0;
        left: 0;
    }
```

Fixed the issues for me.
