### ISSUE TITLE
Publish current version to NPM

### ISSUE THREAD

**Issue by nazar-pc** [PolymerElements/app-layout#537]
Publish current version to NPM, please.
Otherwise since these components try to load Polymer on its own I end up with one instance loaded from Bower and the other from NPM and everything goes to hell.

This is primarily the issue of direct referencing for Polymer and other dependencies (awful approach btw, developer should include them on page in some other way) and can't be fixed easily otherwise.

**Comment by keanulee** [comment]
We are working to release the 3.0 version of this element (along with other Polymer Elements) on NPM with Polymer 3.0 (which will all use JS modules instead of HTML Imports). In the meantime, you can try  the pre-releases:

package.json
```json
  "dependencies": {
    "@polymer/polymer": "^3.0.0-pre.4",
    "@polymer/app-layout": "^3.0.0-pre.4",
```

**Comment by nazar-pc** [comment]
Pre-peleases don't work with Polymer 2.x and I don't want to use Polymer 3 yet, since I'll have a lot of other issues.
Why can't you publish current 2.x version to NPM?

**Comment by justinfagnani** [comment]
The path convention that we use in 2.x doesn't generally work on npm. Our solution for publishing to npm is Polymer 3.0 and related elements.
