### ISSUE TITLE
Changing "narrow" of app-drawer-layout in Polymer 3

### ISSUE THREAD

**Issue by EliArtist** [PolymerElements/app-layout#542]
When changing responsive-width or force-narrow dynamically with data bindings the layout won't rerender properly.
So when switching from wide layout to narrow layout, the app-header stays "narrow", so at the upper left there is a gap. Calling notifyResize or resetLayout is not doing anything.
I'm currently using the Polymer 3 preview (pre12 at the moment) components.

**Comment by keanulee** [comment]
Wasn't able to reproduce this with [polymer-starter-kit#3.0-preview](https://github.com/Polymer/polymer-starter-kit/blob/3.0-preview/src/my-app.js) after updating to pre.12 dependencies - switching between wide/narrow layout works, and adding `responsive-width` and `force-narrow` bindings from my-app to app-drawer-layout seems to works. Repro needed for further debugging.
