### ISSUE TITLE
Bower install no longer works

### ISSUE THREAD

**Issue by patsawz** [PolymerElements/app-layout#549]
### Description
Running `bower install` on this component no longer works. This is because `PolymerElements/font-roboto#^1.0.0` no longer exists on Bower.

### Expected outcome

`bower install` completes successfully.

### Actual outcome

Gets an error for not being able to find that tag for that package.

### Steps to reproduce
1. run `bower install` in folder.

**Comment by keanulee** [comment]
We don't register package names on bower - we just use the shorthand to GitHub repos (e.g. `PolymerElements/app-layout`. Just tested locally and works (are you sure you didn't override the ["Shorthand" default](https://bower.io/docs/api/#install)?).

```
➜  app-layout git:(master) bower i
...
bower cached        https://github.com/PolymerElements/font-roboto.git#1.1.0
bower validate      1.1.0 against https://github.com/PolymerElements/font-roboto.git#^1.0.0
...
bower install               font-roboto#1.1.0

...

font-roboto#1.1.0 bower_components/font-roboto

...

paper-styles#2.1.0 bower_components/paper-styles
├── font-roboto#1.1.0
├── iron-flex-layout#2.0.3
└── polymer#2.6.0
```
