### ISSUE TITLE
How to block parent scroll

### ISSUE THREAD

**Issue by ebatgerel** [PolymerElements/app-layout#553]
### Description
I have a problem with preventing of parent scroll. How can prevent parent scroll ? 

### Expected outcome
Menu appears parent container should block scroll itself.

### Actual outcome
Menu appears parent container scroll working.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by keanulee** [comment]
app-drawer sets `overflow` on `<body>` to `'hidden'` to block its scrolling.
https://github.com/PolymerElements/app-layout/blob/16cdc630ef98e165bfe7ac2b6010da20132deda8/app-drawer/app-drawer.html#L540
You can do something similar if you're using your own element scroller for main content.

**Comment by ebatgerel** [comment]
Sorry, I asked wrong question. How to prevent parent scroll on mobile device.

**Comment by keanulee** [comment]
I don't understand your question.

**Comment by ebatgerel** [comment]
When i see my app on mobile device and i open the navigation and `body` scrolling works.  How to prevent 
`body` scroll when `app-drawer` opened ?
