### ISSUE TITLE
Broken links at https://www.npmjs.com/package/@polymer/app-layout

### ISSUE THREAD

**Issue by sundar-rajavelu** [PolymerElements/app-layout#561]
The links in page (https://www.npmjs.com/package/@polymer/app-layout) under the section "What is inside" --> "Elements" are broken. For example, try the link 'app-drawer'

**Comment by keanulee** [comment]
Those markdown links were written for the [README on GitHub](https://github.com/PolymerElements/app-layout#app-layout--) (which npmjs.com just pulls). Perhaps we could remove them.

**Comment by jsilvermist** [comment]
Isn't removing them a little bit overkill? Why not just add a link back to the github page for NPM users with a note attached?
