### ISSUE TITLE
app-drawer align="bottom" and align="top" not available

### ISSUE THREAD

**Issue by tenacious-joy** [PolymerElements/app-layout#569]
### Description
There's no option to align `app-drawer` to top or bottom

### Expected outcome

There should be an option to align to top and bottom

### Actual outcome

There's no option to align `app-drawer` to top or bottom

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by keanulee** [comment]
We don't plan on supporting this.
