### ISSUE TITLE
app-header threshold-triggered is not reset

### ISSUE THREAD

**Issue by govis** [PolymerElements/app-layout#570]
### Description
When an element containing <code>app-header-layout</code> is removed and added back to the DOM the <code>app-header</code> <code>threshold-triggered</code> attribute is not reset even though app-header-layout is scrolled all the way to the top. 

### Expected outcome
<code>thresholdTriggered is false</code>

![image](https://user-images.githubusercontent.com/971651/48913585-ced53200-ee46-11e8-9aeb-585fe17b3b0a.png)

### Actual outcome
<code>thresholdTriggered is true</code>

![image](https://user-images.githubusercontent.com/971651/48913607-dbf22100-ee46-11e8-81fe-ca7e74f26628.png)

### Live Demo
https://jsbin.com/bopuhozupa

### Steps to reproduce
Open the page in a web browser notice that the header image is visible - <code>thresholdTriggered is false</code>. As you start scrolling it will hide <code>thresholdTriggered is true</code>. Scroll to the bottom and press the "NEXT PAGE" button. Noew page will be created and work the same way. Do it again and now the page comes up without the header image.  

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
I think we can fix this by invoking the code in `AppScrollEffectsBehavior._scrollHandler()` on `attached()`. Need time to do and write tests for this.
