### ISSUE TITLE
app-drawer-layout doesn't apply custom property in a custom element on iPad

### ISSUE THREAD

**Issue by jean-maxime** [PolymerElements/app-layout#572]
### Description
I'm debugging my app on iPad and I've got a problem. I'm loading a file with many properties like colors. If I insert a custom element inside `app-drawer-layout`, my property is not apply. But if I load my custom element outside `app-drawer-layout`, the property is apply. I don't know why it's not apply inside `app-drawer-layout`

### Steps to reproduce

```
<app-drawer-layout force-narrow="true">
	<app-drawer slot="drawer" opened="{{menuOpened}}">
		<my-element></my-element>
	</app-drawer>
<app-drawer-layout>
```

In `my-element` style: 

```
:host {
	background-color: var(--my-color);
}
```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by keanulee** [comment]
Can't seem to reproduce - can you try my demo? https://output.jsbin.com/vusawiq

**Comment by jean-maxime** [comment]
I'm using Chrome 61 and Safari 9 with ios 9.3. Maybe it come from the versions. I'll try tomorrow with a more recent version of ios and browsers.

**Comment by keanulee** [comment]
I tried this on iOS 12 (Chrome version doesn't make a difference on iOS since it's all WebKit anyways). Generally our [support policy](https://polymer-library.polymer-project.org/3.0/docs/browsers) is the last 2 browser versions, but happy to continue helping debug.
