### ISSUE TITLE
how to run shrink template 

### ISSUE THREAD

**Issue by sasikala-tholisam** [PolymerElements/app-layout#576]
### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by sasikala-tholisam** [comment]
http://127.0.0.1:8000/demo/ it is for checking Demo, I need to check Shrink Template, How it should be, where is routes folder

**Comment by keanulee** [comment]
The templates are designed to run as standalone directories, so to run the Shrine template:

```bash
cd templates/shrine
npm install
polymer serve  # served at localhost:8081/
```
